### ISSUE TITLE
Object field access is reported as unused (ast)

### ISSUE THREAD

**Issue by arjantop** [bazelbuild/rules_scala#1011]
When using `dependency_tracking_method = "ast"` object field access does not mark the dependency as used.

rules_scala version: 97997c4d7335d655c0737364a1648a03a083811f

Example repo:
https://github.com/arjantop/rules_scala_bug

Output:
```
INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/arjan/code/rules_scala_bug/BUILD:22:1: scala //:test failed (Exit 1)
error: Target '@maven//:com_twitter_finagle_base_http_2_11' is specified as a dependency to //:test but isn't used, please remove it from the deps.
You can use the following buildozer command:
buildozer 'remove deps @maven//:com_twitter_finagle_base_http_2_11' //:test
one error found
one error found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:256)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:76)
	at io.bazel.rulesscala.worker.GenericWorker.runPersistentWorker(GenericWorker.java:45)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:111)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.548s, Critical Path: 0.18s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by arjantop** [comment]
As #679 I assume you are the right person @Jamie5

**Comment by ittaiz** [comment]
Is this a constant?
If so can you try with version > 2.12.8?

**Comment by arjantop** [comment]
@ittaiz Yes, it works with `2.12.10`. Its a constant.

https://github.com/twitter/finagle/blob/develop/finagle-base-http/src/main/scala/com/twitter/finagle/http/Fields.scala

**Comment by ittaiz** [comment]
I’ll wait for @Jamie5 before I close but I think we just won’t support it

**Comment by Jamie5** [comment]
Yeah this would be at least quite difficult to support pre 2.12.4. Because constants are inlined in the AST and only in 2.12.4 was the original expression made available.

So `unused_dependency_checker_ignored_targets` is probably your friend until you can move off pre-2.12.4.

**Comment by arjantop** [comment]
Thanks, that makes sense. Either way we are close to migrating to 2.12.x. Will try with the scala 2.12.x before reporting a bug next time.
