### ISSUE TITLE
Exclude test targets from instrumentation when running coverage

### ISSUE THREAD

**Issue by kien-truong** [bazelbuild/rules_scala#1042]
Currently, when I run coverage, `scala_test` targets are also instrumented and included in the coverage reports. 

Test targets should not be instrumented unless we set `--instrument_test_targets=true`

**Comment by ittaiz** [comment]
That sounds right.
Are you interested in sending a PR?

**Comment by kien-truong** [comment]
Sorry, I don't think I know enough about bazel and rules_scala to submit a fix for this yet.

**Comment by liucijus** [comment]
Solved in #1147
