### ISSUE TITLE
scalacopts parsing issue with comma

### ISSUE THREAD

**Issue by wisechengyi** [bazelbuild/rules_scala#1049]
Per scalac doc https://docs.scala-lang.org/overviews/compiler-options/index.html: there could be options like `-Ywarn-unused:WARNING1,WARNING2`

However, scala options are joined by comma then split by comma:
https://github.com/bazelbuild/rules_scala/blob/master/scala/private/rule_impls.bzl#L142
https://github.com/bazelbuild/rules_scala/blob/master/src/java/io/bazel/rulesscala/scalac/CompileOptions.java#L39

so if I use `-Ywarn-unused:-implicits,-locals,-explicits,-patvars,-privates` as scalaopts, the build will fail with
```
scalac error: bad option: '-locals'
  scalac -help  gives more information
one error found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:256)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:76)
	at io.bazel.rulesscala.worker.GenericWorker.runPersistentWorker(GenericWorker.java:45)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:111)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
```

**Comment by wisechengyi** [comment]
A couple of options:
1. Write the scalac options into another file to be read by `ScalaCInvoker` which separates the options by newline:
```
-Yabc:x,y,z
-Yefg:alpha,beta
```
2. Use another delimiter such `:::`

@ittaiz @oscar-stripe preferences here?

**Comment by ittaiz** [comment]
Let’s go with a different delimiter.
Chances of `:::` colliding are really low, if that will happen we’ll add the complexity of the file.
Any chance you want to send a PR (with a test of course)?

**Comment by wisechengyi** [comment]
Thanks! Ofc. Just wanted to make sure the approach first 😁
