### ISSUE TITLE
Why does test_disappearing_class appear twice in test_run.sh

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#107]
Hi,
`run_test test_disappearing_class` appears twice in the `test_run.sh` script, is this on purpose? If so why? Additionally do you think a comment might be helpful because for me it was confusing since I thought this might be a bug.

Additionally,
Is there an open issue to track converting test_run.sh to a "proper" bazel test run? I know it's not high on your priority but maybe if it's open someone will grab it.

**Comment by johnynek** [comment]
I don't recall/know any reason. @ianoc ? 

I think it may have been a merge failure. Unless Ian objects, we should just remove the second call.

**Comment by ittaiz** [comment]
btw, apparently #76 is the issue tracking the mentioned conversion

**Comment by ianoc** [comment]
looks like a merge failure to me, 👍 to dropping
