### ISSUE TITLE
Use bazelisk / bazel native instead of our current bazel wrapper

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/rules_scala#1075]
Just noticed [our bazel wrapper](https://github.com/bazelbuild/rules_scala/blob/master/tools/bazel) forces us to download binary of bazel. it’s a mini implementation of [bazelisk](https://github.com/bazelbuild/bazelisk).

I think that:
1. We should commit a file `.bazelversion` with the correct value to repo root. Bazel supports that [since version 2.0.0](https://blog.bazel.build/2019/12/19/bazel-2.0.html#other-important-changes). 
2. Encourage our users to use Bazelisk that respects that `.bazelversion`. Change our CI jobs to use bazelisk like [Greyhound do](https://github.com/wix/greyhound/blob/113fb6152eb112e260b7685db9bb1ec249909694/.circleci/config.yml).
2. CI that want to test other versions can simply change `USE_BAZEL_VERSION` env variable to their liking
4. After doing that we can discuss on whether we want to **force** using bazelisk... but IMHO - we can just run `bazel version` and check if bazelisk was printed, and if not print a nice warning.

Note that [rules_nodejs](https://github.com/bazelbuild/rules_nodejs/) and [rules_python](https://github.com/bazelbuild/rules_python) already started using it.

**Comment by ittaiz** [comment]
Sounds good to me.
What do you mean by force Bazelisk? Why should we force it?

**Comment by or-shachar** [comment]
fixed by #1078
