### ISSUE TITLE
Build is not identical when scala rules compile java sources

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#108]
See example failures in #101 #106 

This seems to only happen on linux. The most common reason is that somehow a timestamp is making it into an output file. We should be able to check by looking at the binary diff to find the actual difference.

We need to fix this because we can't merge a test that makes the build go red, but at the same time, this means currently when using mixed scala/java targets on linux, you will not have optimal caching (each upstream rebuild will invalidate everything downstream).

**Comment by ittaiz** [comment]
my 2c- I thought it doesn't break on OSX just because of #74 but when I changed test_run.sh locally to use `md5` (and not `md5sum`) it didn't break on the only_java_sources branch. I wonder what's going on there...

**Comment by ittaiz** [comment]
also how do you explain #104 not showing the same symptoms? do you think it's somehow order related?

**Comment by ittaiz** [comment]
I'm closing this since we've done a lot of work on this area and I haven't seen any failures or flakiness in this area for a long while.
