### ISSUE TITLE
default instructions are incomplete

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#1083]
If you follow:

https://github.com/bazelbuild/rules_scala#getting-started

and you use `com_google_protobuf` you will get an error like:
```
ERROR: /home/oscar/oss/bosatsu/cli/src/main/protobuf/bosatsu/BUILD:18:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: error loading package '@com_google_protobuf//': Unable to find package for @rules_python//python:defs.bzl: The
repository '@rules_python' could not be resolved.
ERROR: Analysis of target '//cli/src/main/protobuf/bosatsu:bosatsu_proto' failed; build aborted: error loading package '@com_google_protobuf//': Unable to find package for @rules_python//python:defs.bzl: The repository '@rules_python' could not be resolved.
```
So, it seems the user needs to also set up a dependency on a (compatible?) version of rules_python.

I fixed this by adding:
```
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
```

**Comment by or-shachar** [comment]
That's interesting...
@philwo  - is there a best practice with regards of how each rules set provides a list of it's deps (and transitive deps)?

**Comment by philwo** [comment]
@or-shachar Not yet, unfortunately... @meteorcloudy and me are working on it, but it'll take us some more time.

**Comment by or-shachar** [comment]
I do see something in the area: https://docs.bazel.build/versions/3.4.0/skylark/deploying.html#dependencies (thought this doc seems very stale).

**Comment by blorente** [comment]
In the interim (until guidelines are clear), would it be good to add a the necessary dependencies to the "Getting Started" section?
I think it's desirable that "getting started" just works out of the box in a new repo. I'd be willing to make that change to the Readme if needed.

If necessary, to make customization easier, we could add a `transitive_repository_deps.bzl` file to the repo, and define a macro that pulls all the transitive repos.

**Comment by ittaiz** [comment]
I agree. Please send the PR.
