### ISSUE TITLE
Upgrade to bazel 2.2.0

### ISSUE THREAD

**Issue by tian000** [bazelbuild/rules_scala#1091]
I would like to use Go and Scala in the same monorepo, but the bazel minimum version for rules_go is 2.2.0, but the max version for rules_scala (according to README) is 2.0.0.

**Comment by ittaiz** [comment]
I think it's not the max but rather the minimal we know works.
Would you be interested in sending a Travis PR to add the latest bazel version to all builds? This will allow us to know the minimal and the max

**Comment by simuons** [comment]
@tian000 as @ittaiz said `2.0.0` is min version build is run. But there is a build for `latest` bazel version (which currently is `3.4.1`) please see here https://travis-ci.org/github/bazelbuild/rules_scala/jobs/720924785#L217
