### ISSUE TITLE
rules_scala buildkite broken

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_scala#1093]
Looks like Bazel/rules_scala builds are [failing](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1603#e1ce600e-702d-4cce-a628-b4f8508ff837) as of #1068

Snip:

```
File "/var/lib/buildkite-agent/builds/bk-docker-fwx9/bazel-downstream-projects/rules_scala/scala/private/phases/phase_compile.bzl", line 133, column 28, in _phase_compile
--
  | out = _compile_or_empty(
  | File "/var/lib/buildkite-agent/builds/bk-docker-fwx9/bazel-downstream-projects/rules_scala/scala/private/phases/phase_compile.bzl", line 189, column 23, in _compile_or_empty
  | _compile_scala(
  | File "/var/lib/buildkite-agent/builds/bk-docker-fwx9/bazel-downstream-projects/rules_scala/scala/private/rule_impls.bzl", line 197, column 24, in compile_scala
  | ctx.actions.run(
  | Error in run: run() got unexpected keyword argument 'diagnostics_file'
  | (04:03:11) ERROR: Analysis of target '//test/src/main/scala/scalarules/test/large_classpath:dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_dependency_174' failed; build aborted: Analysis of target '//third_party/dependency_analyzer/src/main:scala_version' failed
```

I'm a little confused as to how this commit worked? It looks like like `diagnostic_file` is not a keyword of `ctx.actions.run()`, nor has it ever been. An untested codepath, perhaps?

**Comment by c-parsons** [comment]
@andrefmrocha @illicitonion

**Comment by andrefmrocha** [comment]
This is related to [this addition](https://github.com/bazelbuild/bazel/pull/11766) that's going to happen to bazel. @ittaiz suggested it would be a good idea to merge this down either way with a condition to check if a development version of bazel is being used. I'm assuming this happens because the build is using a development version of bazel

**Comment by c-parsons** [comment]
gating the use of this feature only on whether a development version of bazel is precarious, for this reason :(

Perhaps we can guard this code path with an additional mechanism, for example a build option?

**Comment by andrefmrocha** [comment]
Ah yeah that should be simple enough to do as well, since there's already a toolchain flag to enable this. Tomorrow I'll open a PR for that!
