### ISSUE TITLE
improve handling of java exports

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#11]
They should be exported to skylark in the next release after 0.2.0:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/CRd1BbkHVUw/X6KgxPgjIAAJ

at this location:
https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L177

The issue now is that we always pull the transitive compilation deps for java libraries, which hides dependencies from bazel.

**Comment by ittaiz** [comment]
@johnynek this is solved right?
