### ISSUE TITLE
How to customize reporter for scala_test?

### ISSUE THREAD

**Issue by viclovsky** [bazelbuild/rules_scala#1111]
Rules_scala uses hardcoded reporter : [io.bazel.rules.scala.JUnitXmlReporter](https://github.com/bazelbuild/rules_scala/blob/96f9d94cdbdcc09422a0aa6d9a7aeb256c181b26/scala/private/phases/phase_runfiles.bzl#L19) .

We need to customize report type as colors/full_stacktraces attributes (https://github.com/bazelbuild/rules_scala/blob/eabb1d28fb288fb5b15857260f87818dda5a97c8/scala/private/rules/scala_test.bzl#L58). 

Could you add such customization? 
Or is there any alternative way to customize report?

**Comment by liucijus** [comment]
@viclovsky any chances you can send a PR for such configuration?
