### ISSUE TITLE
scala3 artifact names

### ISSUE THREAD

**Issue by dsilvasc** [bazelbuild/rules_scala#1115]
Hello,

Just as an FYI, the scala 3 compiler and standard library will be published to the current Maven group (`org.scala-lang`) but under new artifact names (`scala3-compiler` and `scala3-library` instead of `scala-compiler` and `scala-library`).

Announcement:
https://contributors.scala-lang.org/t/dotty-artefacts-naming-change/4532

Will rules_scala need any changes to support the new naming scheme?

**Comment by ittaiz** [comment]
no. in bazel the artifact Id is not a big factor (which has good and bad sides) so this won't be an issue.
Thanks a lot for checking in though!
