### ISSUE TITLE
Update version of third party dependency `scrooge_generator` to version 20.9.0

### ISSUE THREAD

**Issue by cattibrie** [bazelbuild/rules_scala#1131]
### Problem
**rules_scala** uses 2 years old version (18.6.0) of **scrooge_generator**. 
Keeping third party dependencies up-to-date is healthy for the project. 

**Main motivation:** Twitter uses the latest version of scrooge. 
Currently, **rules_scala** do not support a lot of features that are available in the latest scrooge for Twitter developers, e.g. parsing of the compiler_args, `--java_passthrough` flag doesn't exist in the version 18.6.0 of scrooge-generator.

### Solution
Update scrooge to the latest version and keep it up-to-date.
Twitter is happy to be responsible for keeping this third party up-to-date.

**Comment by wisechengyi** [comment]
For context there shouldn't be any breaking changes since 18.6.0 per https://twitter.github.io/scrooge/changelog.html

**Comment by ittaiz** [comment]
Sounds good to me. We should probably wait a bit with the merge to give people time to react (and well done on the slack message) but I think we should do it.
