### ISSUE TITLE
Valid Java 8 code reports errors when building

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/rules_scala#1154]
I try to build code, that includes inputs to valid Java 8 classes, like sun.misc.BASE64Encoder.
In current master this fails.
Previously (e.g. versions: fb6e0f0c9383816bddccdbb1e04c90f51a8edb89, a95c54dd1dc197655ee610f5c51f0826c032d4c9) this was working. I use Scala 2.11.

```
MyClass.scala:3: error: object BASE64Decoder is not a member of package sun.misc
import sun.misc.{BASE64Decoder, BASE64Encoder}
       ^
```

I have provided `"-target:jvm-1.8"` in scalacopts for scala_library.

**Comment by liucijus** [comment]
Thanks for reporting @gergelyfabian

**Comment by liucijus** [comment]
These classes were removed from JDK 11. I assume you're expecting your code to compile with JDK 11?

**Comment by gergelyfabian** [comment]
No, I'd like to compile my code with JDK 8, and that was working so far.

I'd have another question though. I see scala_toolchain was introduced, that also has scalacopts parameter. Should the target be also set there?

**Comment by liucijus** [comment]
`"-target:jvm-1.8"` is telling which byte code version to produce, it does not pick the runtime. Judging from the error you get, you're on JDK 11, which can't find JDK 8 classes removed from later versions.

**Comment by gergelyfabian** [comment]
I have also set up Java 8 in .bazelrc:

`build --javabase=@openjdk8_linux_archive//:runtime
run --javabase=@openjdk8_linux_archive//:runtime`

**Comment by liucijus** [comment]
Working example: https://github.com/liucijus/bazel-scala211-jdk8

**Comment by gergelyfabian** [comment]
Thank you! I found the missing pieces in my code thanks to your example.
