### ISSUE TITLE
copy the worker protobuf to the local repo

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#116]
see: https://github.com/bazelbuild/bazel/issues/1995#issuecomment-264062819

it seems the protocol is stable, so rather than pulling the giant repo, we should just copy the protobuf an rebuild that part locally.

Thoughts @ianoc ?

**Comment by ittaiz** [comment]
@johnynek wdyt about Ulf's [comment](https://github.com/bazelbuild/bazel/issues/1995#issuecomment-271544851) about just copying the protobuf? Also do you know what's needed to get "the protobuf runtime to encode / decode from the binary protocol)."?

**Comment by johnynek** [comment]
I think copying the protobuf is fine, we just need to set the build up correctly. I assumed decoding the binary protocol is pretty straight forward, but haven't worked with protobuf much (only thrift).

**Comment by johnynek** [comment]
closed by #123
