### ISSUE TITLE
Scrooge --finagle

### ISSUE THREAD

**Issue by arjantop** [bazelbuild/rules_scala#117]
Is it possible to generate finagle services with current scrooge support? (like passing --finagle in sbt plugin)

**Comment by johnynek** [comment]
I don't think so, but it probably wouldn't be too hard to add. Happy to
help suggest how to make a change in a PR if you have time to submit one.

**Comment by arjantop** [comment]
Just hacked together a "fix": https://github.com/arjantop/rules_scala

Only experimenting now, will probably try to add this once I get the feel how things work/fit together.

**Comment by johnynek** [comment]
great. Would love a PR when it is working well for you.

**Comment by kevingessner** [comment]
@arjantop Did you submit a PR for this?  I'm in search of same finagle support.

**Comment by arjantop** [comment]
@kevingessner sorry, no, did not really have time to do this (experimenting with bazel was just my hobby project)

**Comment by johnynek** [comment]
@kevingessner any interest in a PR that adds that as an option to scooge targets and correctly sets up the finagle dependency when it exists?

**Comment by kevingessner** [comment]
That would be great.  I have a branch that enables the finagle flag, but it's not on top of rules_scala master (because of the new bazel 0.5.3 requirement).  I'll try to get it in shape next week and submit it.
