### ISSUE TITLE
rules_scala CI broken with Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_scala#1211]
Sample breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1903#fe2ada5b-1ca7-486e-8840-ee4175e2c2cd

Sample error:
```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/third_party/dependency_analyzer/src/main/BUILD:6:39: in scala_library_for_plugin_bootstrapping rule //third_party/dependency_analyzer/src/main:scala_version:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/scala/private/rules/scala_library.bzl", line 137, column 22, in _scala_library_for_plugin_bootstrapping_impl
  | return run_phases(
  | File "/var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/scala/private/phases/api.bzl", line 70, column 32, in run_phases
  | new_provider = function(ctx, current_provider)
  | File "/var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/scala/private/phases/phase_compile.bzl", line 47, column 34, in phase_compile_library_for_plugin_bootstrapping
  | return _phase_compile_default(ctx, p, args)
  | File "/var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/scala/private/phases/phase_compile.bzl", line 105, column 26, in _phase_compile_default
  | return _phase_compile(
  | File "/var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/scala/private/phases/phase_compile.bzl", line 130, column 28, in _phase_compile
  | out = _compile_or_empty(
  | File "/var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/scala/private/phases/phase_compile.bzl", line 186, column 23, in _compile_or_empty
  | _compile_scala(
  | File "/var/lib/buildkite-agent/builds/bk-docker-zx07/bazel-downstream-projects/rules_scala/scala/private/rule_impls.bzl", line 194, column 24, in compile_scala
  | ctx.actions.run(
  | Error in run: run() got unexpected keyword argument 'diagnostics_file'
```

Strangely enough, I can't find any evidence that `diagnostics_file` has ever been a parameter of `ctx.actions.run()`, nor is it as an experimental feature.

Is it possible this codepath has always been broken in anticipation of a feature, and this is being now triggered in Bazel@HEAD builds but wasn't before? The logic to assess this code path is:

```
 if len(BAZEL_VERSION) == 0 and enable_diagnostics_report: 
```

Perhaps as of recently BAZEL_VERSION is 0 for Bazel@HEAD builds?

Regardless, I think the easiest solution is to disable this (broken) codepath for now.

**Comment by liucijus** [comment]
Thanks for opening this issue @c-parsons!

@andrefmrocha do you have time to look into this?

**Comment by andrefmrocha** [comment]
> Is it possible this codepath has always been broken in anticipation of a feature, and this is being now triggered in Bazel@HEAD builds but wasn't before?

I think that should be the case of what's happening here. I will open a PR for this. 



> Strangely enough, I can't find any evidence that `diagnostics_file` has ever been a parameter of `ctx.actions.run()`, nor is it as an experimental feature.

This has been related to the work of outputting diagnostics through the BEP that was being done here: https://github.com/bazelbuild/bazel/pull/11766 . At the time, this was being worked on at the same time as this feature, but I, unfortunately, haven't had any feedback on it for quite a while now.
