### ISSUE TITLE
test_coverage_on broken on Bazel@HEAD

### ISSUE THREAD

**Issue by comius** [bazelbuild/rules_scala#1218]
Sample breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1914#d05d4df0-f845-4703-bc08-dc636ee1137a

Sample error:

12,13c12,14

```
12,13c12,14
< BA:5,2
< BRF:1
---
> BRDA:5,0,0,0
> BRDA:5,0,1,1
> BRF:2
16c17
< DA:5,4
---
> DA:5,1
18c19
< DA:7,4
---
> DA:7,1
34,35c35,36
< DA:5,12
< DA:8,4
---
> DA:5,1
> DA:8,1
52c53
< DA:9,4
---
> DA:9,1
66c67
< DA:5,3
---
> DA:5,1
84,85c85,86
< DA:5,9
< DA:7,4
---
> DA:5,1
> DA:7,1
101,103c102,104
< DA:5,6
< DA:9,8
< DA:41,4
---
> DA:5,1
> DA:9,1
> DA:41,1
[0;31m Test "test_coverage_on" failed [0m (2 sec) [0m
Traceback (most recent call last):
  File "bazelci.py", line 3371, in <module>
    sys.exit(main())
  File "bazelci.py", line 3351, in main
    bazel_version=task_config.get("bazel") or configs.get("bazel"),
  File "bazelci.py", line 1067, in execute_commands
    execute_shell_commands(task_config.get("shell_commands", None))
  File "bazelci.py", line 1463, in execute_shell_commands
    execute_command([shell_command], shell=True)
  File "bazelci.py", line 2055, in execute_command
    args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
```

**Comment by liucijus** [comment]
@comius this shows that coverage output changes between Bazel versions. Is there a known practice how to handle such difference in tests?

**Comment by comius** [comment]
So those tests were added 16 days ago, here 6f2df55aacbd89b9ce33f8f447696900f07bac96.
As far as I remember the change in coverage happened mid 2020, I'll try to bisect it.

> @comius this shows that coverage output changes between Bazel versions. Is there a known practice how to handle such difference in tests?

Hm, the appears the test results depend on bazel version and that there's no way around it?

**Comment by liucijus** [comment]
> So those tests were added 16 days ago, here [6f2df55](https://github.com/bazelbuild/rules_scala/commit/6f2df55aacbd89b9ce33f8f447696900f07bac96).

These tests existed before, they just were moved here from Travis configuration (where they would only pass on 3.5.0).  

> As far as I remember the change in coverage happened mid 2020, I'll try to bisect it.

I think it's expected that coverage is different between versions: Bazel comes with bugfixes or new Jacoco versions improve Scala coverage support.

> It appears the test results depend on bazel version and that there's no way around it?

For now I've extracted coverage tests to be running only on `3.5.0`, and hopefully "hacks" like #1205 will provide useful feedback when new Bazel version is released.

**Comment by comius** [comment]
This appears to be fixed, next failing test reported here https://github.com/bazelbuild/rules_scala/issues/1224.
