### ISSUE TITLE
java_toolchain_javacopts_are_used broken on Bazel@HEAD

### ISSUE THREAD

**Issue by comius** [bazelbuild/rules_scala#1224]
Sample breakage:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1921#8da03de5-6707-4ba4-8dd8-189f3ab6c577

```
running test java_toolchain_javacopts_are_used
  
Log:
  
"bazel build --java_toolchain=//test_expect_failure/compilers_javac_opts:a_java_toolchain --verbose_failures //test_expect_failure/compilers_javac_opts:can_configure_jvm_flags_for_javac_via_javacopts" should have failed with message "invalid flag: -InvalidFlag" but did not.
 Test "java_toolchain_javacopts_are_used" failed  (0 sec)
```

**Comment by Wyverald** [comment]
Looks like this is still failing, albeit with a slightly different error message:

```
"bazel build --java_toolchain=//test_expect_failure/compilers_javac_opts:a_java_toolchain --verbose_failures //test_expect_failure/compilers_javac_opts:can_configure_jvm_flags_for_javac_via_javacopts" should have failed but passed.
--
  | Test "java_toolchain_javacopts_are_used" failed  (0 sec)
```

link: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1928#fcb36429-c92a-408a-b032-63cbeb2a87f6

**Comment by meteorcloudy** [comment]
rules_scala has been disabled in Bazel downstream, but you can still check its status with Bazel@HEAD at https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/848

**Comment by ittaiz** [comment]
@liucijus @simuons are rules_scala maintainers.
Having said that I agree this should be handled but that's just my 2c as part of the community.

**Comment by meteorcloudy** [comment]
Thanks for the fix, I'll re-enable rules_scala in downstream
