### ISSUE TITLE
`scala_junit_test` not working with `bazel coverage`

### ISSUE THREAD

**Issue by virusdave** [bazelbuild/rules_scala#1238]
Description of the problem / feature request:
Add coverage_runfiles phase and _lcov_merger attr to scala_junit_test

Feature requests: what underlying problem are you trying to solve with this feature?
bazel coverage on bazel 4.0 barfs on scala_junit_test target types, seemingly because it's missing this phase.

Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Create a scala_junit_test target
Run bazel coverage on that target

This can be seen in this repo via `bazel coverage //test:JunitTestWithDeps`

What operating system are you running Bazel on?
OSX Catalina

What's the output of bazel info release?
release 4.0.0

Extra info
I've manually modified the rules_scala sources to do this, and it suddenly starts to work. I've also used the custom phase mechanism to build a custom scala_junit_test rule which does the same thing, and this also works. It's what I'm using now internally until upstream has a similar change.

**Comment by liucijus** [comment]
@virusdave, thanks for reporting! Will you be able to prepare a PR too?

**Comment by liucijus** [comment]
> @virusdave, thanks for reporting! Will you be able to prepare a PR too?

Oh, I see there is #1239, thanks!

**Comment by liucijus** [comment]
Solved by #1250
