### ISSUE TITLE
Trying to build scalikejdbc

### ISSUE THREAD

**Issue by rockwotj** [bazelbuild/rules_scala#124]
I've just included their library and get a huge exception with the following error:

```
Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file scalikejdbc/SQLInterpolationMacro$
 ```

Seems to be an issue with macros? I've wrapped the code in a macro library, but that doesn't seem to work. Is that because the macro is coming from an external jar?

**Comment by johnynek** [comment]
Can you take a look at other issues about macros? The answer is for macros,
you cannot use /jar targets and must use /file targets for maven artifacts.
For your own macros you need to use scala_macro_library

**Comment by rockwotj** [comment]
Thx.
