### ISSUE TITLE
Wrong file exported from `scala_config`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_scala#1245]
In `scala_config`, the [generated build file exports "def.bzl"](https://github.com/bazelbuild/rules_scala/blob/master/scala_config.bzl#L8) yet the file written is "[config.bzl](https://github.com/bazelbuild/rules_scala/blob/master/scala_config.bzl#L19)"

Presumably, both of these are meant to match, but I'm not sure which way round they should be: `config.bzl` or 'def.bzl`?

**Comment by liucijus** [comment]
@shs96c thanks for reporting! It should be `config.bzl`. Probably that export_files statement can be removed - there's only single file created by the repository rule, and the file is generated which makes it hard to spot such mistakes.

**Comment by simuons** [comment]
Fixed as part of https://github.com/bazelbuild/rules_scala/pull/1259
