### ISSUE TITLE
Must the protobuf compiler be built from sources before a simple scala_binary?

### ISSUE THREAD

**Issue by samolisov** [bazelbuild/rules_scala#1254]
Hello the rules_scala team. 

I'm trying to build a simple `scala_binary` rule:

```bzl
scala_binary(
    name = "hello-bin",
    srcs = glob(["*.scala"]),
    main_class = "Hello"
)
```

My command line:
```sh
bazel run -c opt --jobs 4 hello-bin
```

But the first thing Bazel is doing is the compiling of protobuf compilers for many languages:
```
Compiling src/google/protobuf/compiler/command_line_interface.cc [for host]; 3s local
Compiling src/google/protobuf/compiler/cpp/cpp_file.cc [for host]; 2s local 
```

This is a piece of C++ code, well I have a C++ compiler on my machine, but this is not a thing that must be expected by any Java/Scala developer. There is no any protobuf in my hello world project and I use no `scala_proto_library` in the build configuration. 

Can you make the protobuf an optional dependency that will be taken into account only when the `scala_proto_library` rule presents? I believe it can gain better user experience for your amazing project.

Bazel version: bazel 4.0.0
OS: Windows 10

**Comment by simuons** [comment]
Hi @samolisov,

`protobuf` is used internally by `rules_scala` and cannot be avoided at the moment.

However you can avoid compiling it and use released binaries. To do so you need to declare `rules_proto` repository and it's dependencies before `rules_scala` [like here](https://github.com/bazelbuild/rules_scala/blob/master/WORKSPACE#L14-L31).

**Comment by samolisov** [comment]
@simuons Thank you for the suggestion. The solution works fine, the initial build of my project has been much faster.

**Comment by thundergolfer** [comment]
For others arriving here late, @simuons's link is mutable (pointing at `master`). The code originally referneced is https://github.com/bazelbuild/rules_scala/blob/475cc5b2379c4b08f81359e12399bf6d171b5636/WORKSPACE#L14-L31

**Comment by a4z** [comment]
Is there any news on that? 
I still get protobuf always compiled, no matter what I try 
That is kind of annoying because that is super slow, for a relatively small scala project that builds with sbt in 2 minutes,  the bazel build takes 8 on CI (github actions)
