### ISSUE TITLE
Discuss alternatives to include resolution strategy 

### ISSUE THREAD

**Issue by adam-singer** [bazelbuild/rules_scala#1255]
Highlighted in https://github.com/twitter-forks/rules_scala/pull/14 we are looking for alternatives to how resolution strategy works for `include` statements in thrift. `Compiler` and `FocusedZipImporter` diverge a bit in behavior of how resolution based on the set of importers used. `rules_scala` has a stricter interpretation of absolute path definition baked into the packaged jar/zip file. 

Our problem is focused around authors of thrift files don't always use the same exact `include` path because current resolution strategy in scrooge cli allows for it. Example `include "a/b/c.thrift"` and `include "b/c.thrift"` can resolve to the same file if the file is part of the dependency.  

Given a strategy of resolution for scrooge users is based on how scoorge cli generally handles it, it would be useful for that behavior to also exist in `rules_scala`.  https://github.com/twitter-forks/rules_scala/pull/14 introduces that behavior, but would like to open a discussion about upstreaming it. I think one way we could upstream it is hiding this behind a flagged parameter so existing users don't opt into a new resolution strategy. It happen to be more users disable [addRootDirImporter|https://github.com/twitter/scrooge/blob/develop/scrooge-generator/src/main/scala/com/twitter/scrooge/Compiler.scala#L57] which might make removing flag/behavior in the future so thrift users have a "standard" way to use / reference include statements.

Looking for feedback and thoughts about introducing an upward path traversal strategy to `rules_scala`.

**Comment by liucijus** [comment]
@ittaiz do you know who should be added to this discussion? Who uses thrift? 
@adam-singer I bet posting about this issue on #scala @ Bazel Slack may draw attention from more folks.

It would be great if we can find someone who can own scrooge/thrift area in Rules Scala (de facto looks like Twitter folks, maybe there are other companies who haven't contributed lately).

**Comment by ittaiz** [comment]
stripe folk have a big interest in thrift (cc @andyscott) there were others but to be honest I don't really remember.
@dinowernli do you also use thrift?

**Comment by adam-singer** [comment]
Discussion also opened at https://bazelbuild.slack.com/archives/CDCKJ2KFZ/p1616742942017700

**Comment by adam-singer** [comment]
This issue didn't seem to pick up any discussion, going to close it for now.

**Comment by liucijus** [comment]
@adam-singer if you think this include resolution is not what all users want, maybe it can be controlled with a feature toggle?
