### ISSUE TITLE
Worker process did not return a `WorkerResponse`

### ISSUE THREAD

**Issue by sierikov** [bazelbuild/rules_scala#1256]
Hi! 

I'm new to Bazel with Scala and use this amazing repository in my project. My task is to migrate a project from `sbt` to `bazel`. But I've faced a few weeks ago with `WorkerResponse` issue.

Versions:
| Technologie   |      Version      | 
|:----------|:-------------|
| `scala` |  `2.12` | 
| `rules_scala` |    `5df8033f752be64fbe2cedfd1bdbad56e2033b15`   |
| `bazel` | `bazel 4.0.0-homebrew` | 

I've already asked this question [on StackOverflow](https://stackoverflow.com/questions/66640581/bazel-scala-failed-worker-process-did-not-return-a-workresponse) but there is still no response/comment/answer. 

Short:
1. Define the dependency
2. Load the dependency
3. Add to `scala_library` in `deps`
4. Run `bazel build //<package>:<name-of-lib>`
5. Receive the error: `failed: Worker process did not return a WorkResponse:`
6. And the error of JVM: `Caused by: java.lang.ClassNotFoundException: io.bullet.borer.deriver.Deriver`

For more details please see [the question on StackOverflow](https://stackoverflow.com/questions/66640581/bazel-scala-failed-worker-process-did-not-return-a-workresponse).

This could be my stupidity or the `rules` bug 😅. Maybe together we can figure this out.

**Comment by liucijus** [comment]
@sierikov please check links in your report - they lead to this repository. I guess you have misconfigured something in your project's deps. Could you make a public repo which demonstrates the problem?

**Comment by sierikov** [comment]
Thanks for the quick response! I fixed the links to StackOverflow in the first message. I will prepare the example repository and send it here when it's ready.

**Comment by liucijus** [comment]
@sierikov maybe what you need is to use `scala_macro_library` instead of `scala_library`?

**Comment by sierikov** [comment]
I have tried that. The same result.

**Comment by sierikov** [comment]
I have done a little repo with the problems, that I have faced. Here is the link [sierikov/b1256](https://github.com/sierikov/b1256)

**Comment by liucijus** [comment]
@sierikov `spark` val seems to be initialized. For dependency related problems you can try "plus-one" mode, default toolchain is "direct", or try adding all direct deps:
```
deps = [
        "@some_maven//:org_apache_spark_spark_core_2_12",
        "@some_maven//:org_apache_spark_spark_sql_2_12",
        "@some_maven//:org_apache_spark_spark_catalyst_2_12",
]
```

**Comment by sierikov** [comment]
I have tried that, but without `catalyst`. I'll try with it. Thanks.

**Comment by sierikov** [comment]
Perfect! Defining all needed direct dependencies solves the problem, thank you! I will also add a fix to the repository,
