### ISSUE TITLE
error: can't expand macros compiled by previous versions of Scala

### ISSUE THREAD

**Issue by Huang77** [bazelbuild/rules_scala#127]
When i use bazel to build my project, there is an error "can't expand macros compiled by previous versions of Scala", is there any solution which i dont need to modify my code ?

**Comment by johnynek** [comment]
Please search issues for macros or see the README for some discussion. Macro jars need special handling.

**Comment by Huang77** [comment]
I think it is the scala version that cause the problem. Bazel uses scala 2.11, but the jars I used is 2.10.4.   Did you have problems like this before?

**Comment by johnynek** [comment]
Oh. The rules currently only support 2.11. We have a ticket to support
2.12. Supporting 2.10 is not a high priority.

You can't mix scala versions in jars.
