### ISSUE TITLE
Custom JacocoRunner scripts fail

### ISSUE THREAD

**Issue by BillyAutrey** [bazelbuild/rules_scala#1277]
If you run these scripts as is, you will get a few problems.

1. The bazel master branch is now much further ahead.  This causes the patch to be irrelevant, because the existing jacoco 0.8.6 jars in the bazel target directory are the ones used to build the JAR.
2. The `coverage_local_jacocorunner/test.sh` script assumes that tests are in the `coverage` directory.  The code that is tested has since moved.
3. The `expected-coverage.dat` file in the same folder needs to be updated for the new test directory, as well.

Fixes:

1. Change the bazel portion of the compilation script to check out the `4.1.0` tag instead of `master`.
2. Change the `test_coverage_with_local_jacocorunner()` function in `coverage_local_jacocorunner/test.sh`  to use `//test/coverage_scalatest:test-scalatest` instead.
3. Change all references to `coverage` in `expected-coverage.dat` to `coverage_scalatest`.

**Comment by BillyAutrey** [comment]
I have fixes for this, PR incoming.

**Comment by liucijus** [comment]
fixed in #1278
