### ISSUE TITLE
Scala equivalent of rules_jvm_external java_export

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/rules_scala#1292]
This is rather a question.

Is there support for publishing Scala artifacts like there is support for Java artifacts in rules_jvm_external: `java_export`.

https://github.com/bazelbuild/rules_jvm_external#publishing-to-external-repositories

Would it be enough to wrap a `scala_library` in `java_export`?

**Comment by liucijus** [comment]
I didn't try it myself, but it should work. Also, have you seen this text: https://github.com/bazelbuild/rules_scala/blob/master/docs/publish_to_maven.md
