### ISSUE TITLE
Wrong URL on bazel.io

### ISSUE THREAD

**Issue by JD557** [bazelbuild/rules_scala#13]
On http://bazel.io/docs/be/scala.html, it says that the page was moved to https://github.com/bazelbuild/rules_scala/blob/master/README.html, although the correct URL is https://github.com/bazelbuild/rules_scala/blob/master/README.md (replace `.html` with `.md`)

**Comment by damienmg** [comment]
This is fixed I think it should appear on next push. Sorry for the error!
