### ISSUE TITLE
Non-reproducible build with scala_proto_library

### ISSUE THREAD

**Issue by darl** [bazelbuild/rules_scala#1311]
## Problem

Scalac sometimes embeds file path in compiled class (look for `tmp514266449445771254` part):
```
javap -v $PWD/.../ErrorCode\$UNKNOWN_ERROR\$.class | grep bazel-out
   #40 = Utf8               Uninitialized field: bazel-out/k8-fastbuild/bin/schema-registry/proto/.../tmp514266449445771254/.../ErrorCode.scala: 22
   #41 = String             #40           // Uninitialized field: bazel-out/k8-fastbuild/bin/schema-registry/proto/.../tmp514266449445771254/.../ErrorCode.scala: 22
   #47 = Utf8               Uninitialized field: bazel-out/k8-fastbuild/bin/schema-registry/proto/.../tmp514266449445771254/.../ErrorCode.scala: 23
   #48 = String             #47           // Uninitialized field: bazel-out/k8-fastbuild/bin/schema-registry/proto/.../tmp514266449445771254/.../ErrorCode.scala: 23
        20: ldc           #41                 // String Uninitialized field: bazel-out/k8-fastbuild/bin/schema-registry/proto/.../tmp514266449445771254/.../ErrorCode.scala: 22
        20: ldc           #48                 // String Uninitialized field: bazel-out/k8-fastbuild/bin/schema-registry/proto/.../tmp514266449445771254/.../ErrorCode.scala: 23
```

ScalacWorker creates temporary directory if `srcjar` is given:
https://github.com/bazelbuild/rules_scala/blob/e21dd301e96e6f9146cfcbe820c37e2c9d194b93/src/java/io/bazel/rulesscala/scalac/ScalacWorker.java#L108

It's common to see `scrjar`s in scalapb compilation.

## Possible solution
Create temporary directory's name more predictably.
It can be hash of it's short_path or something similar.

**Comment by simuons** [comment]
Hi @darl, thanks for reporting this.

You mentioned
> Scalac sometimes embeds file path in compiled class

Maybe you know under what circumstances it does that and why? I tried looking (with javap) at few compiled classes in rules_scala and couldn't find source paths being embedded.

Maybe you could provide repro?

I have a [PR](https://github.com/bazelbuild/rules_scala/pull/1315) which addresses that but need to understand this issue fully and make sure this is right thing to do.

**Comment by darl** [comment]
In my case its result of compilation of proto enums.
It compiles into `case objects`.

Minimal example taken from scalac tests (https://github.com/scala/scala/blob/8a2cf63ee5bad8c8c054f76464de0e10226516a0/test/files/run/checkinit.scala)

```bash
$ cat test.scala
trait U {
  val a = b
  def b: AnyRef
}

class U1 extends U { val b = "" }

$ scalac -Xcheckinit $PWD/test.scala && javap -v 'U1.class' | grep test.scala
  Compiled from "test.scala"
   #7 = Utf8               test.scala
  #24 = Utf8               Uninitialized field: /Users/darl/test.scala: 6
  #25 = String             #24            // Uninitialized field: /Users/darl/test.scala: 6
        22: ldc           #25                 // String Uninitialized field: /Users/darl/test.scala: 6
        22: ldc           #25                 // String Uninitialized field: /Users/darl/test.scala: 6
SourceFile: "test.scala"

```

**Comment by simuons** [comment]
Hi @darl 

could you verify it's working for you and close this issue?

There was a regression https://github.com/bazelbuild/rules_scala/issues/1322 which was fixed in https://github.com/bazelbuild/rules_scala/pull/1323

**Comment by darl** [comment]
I haven't tested for reproducibility yet.
But atleast it compiles fine.
