### ISSUE TITLE
Using scalatest and zio specs in the same workspace

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/rules_scala#1318]
I'd like to use Zio specs (https://github.com/zio/zio/blob/master/docs/usecases/testing.md) with Bazel in a workspace where I already use ScalaTest.

The existing sbt setup to import Zio Testframework is this: `testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework")`

Zio docs say: "A custom JUnit runner is provided for running ZIO Test specs under other build tools (like Maven, Gradle, Bazel, etc.)".

When looking testing docs for rules_scala (https://github.com/bazelbuild/rules_scala/blob/master/docs/testing.md) I started wondering whether I should use two different toolchains or one common toolchain for junit and scalatest.

```
# Can I use both of these? Or do I need to create one toolchain that combines both?

# JUnit 4
load("@io_bazel_rules_scala//testing:junit.bzl", "junit_repositories", "junit_toolchain")
junit_repositories()
junit_toolchain()

# ScalaTest
load("@io_bazel_rules_scala//testing:scalatest.bzl", "scalatest_repositories", "scalatest_toolchain")
scalatest_repositories()
scalatest_toolchain()
```

**Comment by gergelyfabian** [comment]
As far as I understand there can be only one toolchain active with type `toolchain_type = "@io_bazel_rules_scala//testing/toolchain:testing_toolchain_type"`...

**Comment by liucijus** [comment]
Are you writing a custom test runner? Or will you use Junit? To have both Junit and Scala Test rules configured, you need to have a combined toolchain with relevant deps_ids.

**Comment by gergelyfabian** [comment]
I think I'll simply use Junit to run Zio specs.

So I should just combine the default Junit and Scala Test toolchains.

**Comment by gergelyfabian** [comment]
I think I managed to set up the combined toolchain for both scalatest and junit.

The test however is still not being executed.

Should I add Zio dependencies also to the classpath providers? Do I need to modify the scala_test target so that it executes tests with junit?

**Comment by gergelyfabian** [comment]
As written in the docs: "scala_test generates a Scala executable which runs unit test suites written using the scalatest library. It may depend on scala_library, scala_macro_library and java_library rules." So then what is the supported way to run tests with Junit?

**Comment by gergelyfabian** [comment]
I think I have found it.
I needed to use the `scala_junit_test` rule. It's kind of missing docs, so found it through searching through rules_scala's own tests.

**Comment by gergelyfabian** [comment]
Btw. I also tested coverage with `scala_junit_test` + Zio. Seems to be working.

**Comment by gergelyfabian** [comment]
Important to note that as Zio docs mention it, you need to change any spec `object` to `class` and extend `zio.test.junit.JUnitRunnableSpec`.

Adding Zio to the toolchain is not necessary when using JUnit.

**Comment by gergelyfabian** [comment]
This is the toolchain that made it work:

```
# Modified version of rules_scala's testing_toolchains_with_all_deps_impl:
scala_testing_toolchain(
    name = "testing_toolchain_with_junit_and_scalatest_impl",
    dep_providers = [
        ":junit_classpath_provider",
        ":scalatest_classpath_provider",
    ],
    visibility = ["//visibility:public"],
)

toolchain(
    name = "testing_toolchain_with_junit_and_scalatest",
    toolchain = ":testing_toolchain_with_junit_and_scalatest_impl",
    toolchain_type = "@io_bazel_rules_scala//testing/toolchain:testing_toolchain_type",
    visibility = ["//visibility:public"],
)

declare_deps_provider(
    name = "junit_classpath_provider",
    deps_id = "junit_classpath",
    visibility = ["//visibility:public"],
    deps = [
        "@io_bazel_rules_scala_junit_junit",
        "@io_bazel_rules_scala_org_hamcrest_hamcrest_core",
    ],
)

declare_deps_provider(
    name = "scalatest_classpath_provider",
    deps_id = "scalatest_classpath",
    visibility = ["//visibility:public"],
    deps = [
        "@io_bazel_rules_scala_scalactic",
        "@io_bazel_rules_scala_scalatest",
    ],
)
```
