### ISSUE TITLE
scala_library: generated *_deploy.jar leaves only one configuration file from dependency jars

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/rules_scala#1320]
I have a case where I have dependencies: A, B, C.
Each have a configuration file at their root: `abc.conf`.

When the `*_deploy.jar` file is created only one of `A.jar!/abc.conf`, `B.jar!/abc.conf` and `C.jar!/abc.conf` is left (frequently some frameworks put some plugin description into the same filename, and do that in several packages).

Is there any solution to have access to all these files, if I have all these as dependencies of my `scala_library` target? Normally I'd be using the `*_deploy.jar` from some scripts.

I'd need to have access to all of the configuration files on the classpath in runtime.

**Comment by simuons** [comment]
Hi @gergelyfabian ,

`rules_scala` uses `@bazel_tools//tools/jdk:singlejar` to merge jars into single `deploy.jar` [here](https://github.com/bazelbuild/rules_scala/blob/master/scala/private/phases/phase_merge_jars.bzl) so need to check if it's allowed to have duplicates by [@bazel_tools//tools/jdk:singlejar](https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar)

I see there is [no_duplicates flag](https://github.com/bazelbuild/bazel/blob/56d624be4dc79a94ed763c07d302c6270bc8c43b/src/tools/singlejar/options.cc#L51) which I assume is [false by default](https://github.com/bazelbuild/bazel/blob/56d624be4dc79a94ed763c07d302c6270bc8c43b/src/tools/singlejar/options.h#L32) and is not set by `rules_scala`

Maybe it depends on bazel version you are using.

**Comment by gergelyfabian** [comment]
The fix on my side became to mark these dependencies as `neverlink`, to exclude them from the `*_deploy.jar` and provide them one-by-one to the classpath separately in my script.
