### ISSUE TITLE
Support auth option for scala_repositories

### ISSUE THREAD

**Issue by caseyduquettesc** [bazelbuild/rules_scala#1321]
Downloading the scala compiler from an internal proxy such as jfrog is impossible without accepting an auth option. I see that it ultimately calls `repository_ctx.download`, which accepts an `auth` dict. Maybe it could be passed through?

**Comment by liucijus** [comment]
@caseyduquettesc have you tried using custom toolchain with dep providers https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_toolchain.md? This allows to set up custom loader for external deps like https://github.com/bazelbuild/rules_jvm_external. Example: https://github.com/liucijus/rules-scala-proto-toolchain/blob/main/BUILD#L42

**Comment by caseyduquettesc** [comment]
Good point, I'll give that a try

**Comment by caseyduquettesc** [comment]
Yep that works!
