### ISSUE TITLE
Support proto3 optional

### ISSUE THREAD

**Issue by brandon-leapyear** [bazelbuild/rules_scala#1337]
proto3 supports optionals by default after 0.15. This library does use a new enough version of protoc:
```
$ bazel run @com_google_protobuf//:protoc -- --version
libprotoc 3.18.0
```
But it seems like the version of scalapb doesn't support this?
```
error.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-scala hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--scala_out:
```

I currently see:
https://github.com/bazelbuild/rules_scala/blob/b85d1225d0ddc9c376963eb0be86d9d546f25a4a/third_party/repositories/scala_2_13.bzl#L133
Should this be updated to 0.11?
* https://github.com/scalapb/ScalaPB/issues/870#issuecomment-654320187

**Comment by liucijus** [comment]
@brandon-leapyear if you are looking to use different version of scalapb in your projects, are you aware that you can use other versions by defining [scala_proto_deps_toolchain](https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_proto_library.md)? Example of such toolchain configuration: https://github.com/liucijus/rules-scala-proto-toolchain (it uses old versions still, but should be trivial to update [here](https://github.com/liucijus/rules-scala-proto-toolchain/blob/main/WORKSPACE#L111-L160)). If you use Rules Scala in production projects eventually you'll need to define your own dependency configuration.
