### ISSUE TITLE
ijar hack revert?

### ISSUE THREAD

**Issue by virusdave** [bazelbuild/rules_scala#1371]
Can this be reverted?
https://github.com/bazelbuild/rules_scala/blob/2437e40131072cadc1628726775ff00fa3941a4a/scala/scala_import.bzl#L7-L9

Looks like the referenced issue was fixed already.

**Comment by johnynek** [comment]
did you try it? Do we have tests for what we are hacking around?

**Comment by liucijus** [comment]
@virusdave thanks for pointing this out. Have you faced any issue with the current implementation, or just bringing this up because of the existing comment?

@johnynek we have tests for the rule and stamping action, but don't look into the jar to validate if ijar works correctly.

**Comment by virusdave** [comment]
> did you try it? Do we have tests for what we are hacking around?

Started to while on the plane yesterday, but it's a little more involved than just uncommenting the code :)  I'll take a whack at figuring it out at some point, unless someone else already knows what's needed.

> Have you faced any issue with the current implementation, or just bringing this up because of the existing comment?
Not really - main issue is the build log spam that PT brought up in the other issue.  While investigating some of the output i ran into this, and saw that the upstream issue had been fixed, which apparently resolved the log spam from another thread.
