### ISSUE TITLE
Resources not included in jar if srcs is empty

### ISSUE THREAD

**Issue by seanmcl** [bazelbuild/rules_scala#138]
The following repo demonstrates a bug in `scala_library`

https://github.com/seanmcl/scala-bazel-bug

I expected the resources files to be included without srcs requiring a non-empty list.

**Comment by johnynek** [comment]
Yeah, filegroup is not supported right now. See the test for how this works:

https://github.com/bazelbuild/rules_scala/blob/master/test/BUILD#L163

the resources should be individual files.

would welcome a PR to add support for filegroup resources.

**Comment by or-shachar** [comment]
@johnynek  - It's not only filegroups. Also just simple:
```
scala_library(
    name = "resources",
    resources = ["a.txt"],
)
```
Does not copy the `a.txt` to the jar.

**Comment by or-shachar** [comment]
fixed and merged

**Comment by ittaiz** [comment]
@seanmcl please reopen if you think this wasn't resolved
