### ISSUE TITLE
Error in pack_sources: in call to pack_sources(), parameter 'output_jar' is deprecated.

### ISSUE THREAD

**Issue by wmeints** [bazelbuild/rules_scala#1406]
I tried setting up a completely new build for my Scala project and ran into a rather cryptic error message:

```
Error in pack_sources: in call to pack_sources(), parameter 'output_jar' is deprecated. and will be removed soon. It may be temporarily re-enabled by setting --incompatible_java_common_parameters=false
```

After adding `--incompatible_java_common_parameters=false` to my `bazel build` command, the project started building correctly. However, I think this may break again in the future when the `output_jar` parameter is completely removed.

Output from `bazel version`:

```
Build label: 5.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 24 14:03:32 2022 (1648130612)
Build timestamp: 1648130612
Build timestamp as int: 1648130612
```

**Comment by simuons** [comment]
Hi @wmeints, are you on latest rules_scala? I believe this should be fixed in https://github.com/bazelbuild/rules_scala/commit/2894ca2c7546b10b3bd7aa3112384749bccbbc0d

**Comment by wmeints** [comment]
I followed the instructions from the README in the main branch. Could it be that the instructions are incomplete?

**Comment by wmeints** [comment]
I changed the version to the commit you mentioned and recalculated the SHA256 hash for the archive. That fixed the issue for me.  The instructions in the README refer to an older version and don't provide clear instructions on how to get the latest greatest.

Is there another source that explains how to keep up to date with the latest version?

**Comment by simuons** [comment]
We don't have releases and rely on commits. Readme goes out of sync on each commit. It serves more like as an example. Definitely it requires improvement. Please update to the latest commit. We will come up with something to improve this.

**Comment by wmeints** [comment]
Thanks a ton! I'll have a think about the README and how it would help me get to the latest version more easily.
