### ISSUE TITLE
Protobuf and gRPC Support

### ISSUE THREAD

**Issue by PranavSathy** [bazelbuild/rules_scala#144]
It would be awesome if there any way to support generating, compiling and linking in gRPC service definitions in Scala (using ScalaPB). 

https://github.com/scalapb/ScalaPB

Is this something could be potentially incorporated into rules_scala?

**Comment by johnynek** [comment]
Yes. It could be. You could see the Twitter Scrooge rules as examples of how you might do this.

**Comment by johnynek** [comment]
@azymnis here is our protobuf/grpc issue. Can you comment here if you are working? I think we have someone at Stripe who will also chime in soon.

**Comment by azymnis** [comment]
@johnynek sure, I could pick this up this week. If anyone else has already done this though or they are close, let me know so we don't do double work

**Comment by azymnis** [comment]
@johnynek @ittaiz here's an ugly way to do this. Bundle scalapb's `spbc` with `rules_scala`: https://github.com/scalapb/ScalaPB/releases

Then we can have a `protopb_library` that will call `spbc` on all `proto_library` targets that it depends on. Does that sound too terrible?

FWIW this seems to be the approach that bazel has taken internally with protobuf and grpc: https://github.com/bazelbuild/bazel/blob/master/third_party/protobuf/BUILD

**Comment by johnynek** [comment]
yeah, that sounds right. I would call it `scala_proto_library` or something. You might want to check out: 

https://github.com/bazelbuild/rules_scala/blob/master/twitter_scrooge/twitter_scrooge.bzl

to see how we did this with scrooge. To "bundle" we point to the jar (or binary if we really have to) that bazel can pull down and run.

**Comment by azymnis** [comment]
I'll start working on this today. If anyone has picked this up already please speak up

**Comment by jxm-stripe** [comment]
I'd not call my work all that close, TBH, mainly due to major unfamiliarity with bazel concepts.

**Comment by azymnis** [comment]
@jxm-stripe do you have a PR up?

**Comment by azymnis** [comment]
@johnynek @ittaiz I think we can close this, right?

**Comment by ittaiz** [comment]
indeed. again thank you for your work!
btw, you might be interested in #650
