### ISSUE TITLE
scalatest 3.2.x stack is missing wordspec dependency

### ISSUE THREAD

**Issue by scoquelin** [bazelbuild/rules_scala#1448]
While trying to migrate our codebase from scalatest `3.1.x` to `3.2.x`, I noticed that the scalatest `ẁordspec` dependency is missing from the stack :

https://github.com/bazelbuild/rules_scala/blob/73f5d1a7da081c9f5160b9ed7ac745388af28e23/scalatest/scalatest.bzl#L12-L23

I will open an MR to fix this !

**Comment by liucijus** [comment]
@scoquelin have you considered using custom testing toolchain where you can customize dep providers to add more deps for ScalaTest?

**Comment by scoquelin** [comment]
I could indeed go that route but seems like the default `scalatest` toolchain already contains most of the dependencies for specs anyway (5/8) so I thought we might want to go all the way to cover all test styles out of the box unless of course there is a strong case against it.

**Comment by scoquelin** [comment]
I managed to use a custom `scalatest` toolchain` to achieve what I was after, thanks for the tip. I can now also filter out which specs I want to use as well as the actual ` scalatest` version which gives a bit more flexibility.
