### ISSUE TITLE
deploy_jar not written

### ISSUE THREAD

**Issue by jawsthegame** [bazelbuild/rules_scala#145]
It looks like a scala_library target should generate a deploy_jar, which I assume is a fat jar. This doesn't seem to be working. All I end up with is the class jar and the ijar.

**Comment by johnynek** [comment]
Did you build the jar explicitly using `bazel build
//my/path/target_deploy.jar`?

The deploy jar is expensive and is only computed if explicitly requested
(as in the java rules).

**Comment by jawsthegame** [comment]
Getting a "no such package" error, and I can't see where that target is getting generated in the rule definition. Wouldn't that have to be part of a macro?

**Comment by johnynek** [comment]
I'm on the phone now, but here is the line that creates it:

https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L262

You can double check that this is supported by scala library, maybe it is
just scala binary. You can also grep the test directory. I thought there
was a test that exercised this.

I'm using it in a few cases (with binary targets) so unless it is a recent
regression it works.

**Comment by jawsthegame** [comment]
Yes, I saw this code. _bulld_deployable is called by _lib, which is in turn called by the impl for scala_library. I tried your suggestion with both library and binary, producing the same error. I'm using the latest commit of the scala rules. Can you tell me which commit you are using?

**Comment by johnynek** [comment]
if you look here:

https://github.com/bazelbuild/rules_scala/blob/master/test/BUILD#L25

this is where it is exercised in the tests, so it should be working currently. Can you show exactly the command you are using to invoke bazel that is failing and the full output?

**Comment by jawsthegame** [comment]
Huge apologies all around. This is of course my screw up.

I was trying `bazel build //path/to/module_deploy.jar` instead of `bazel build //path/to/module:target_deploy.jar...

I was thrown off because my scala_library target is named the same as the module.

Thanks!
