### ISSUE TITLE
rules_scala not compatible with nolegacy_external_runfiles bazel flag

### ISSUE THREAD

**Issue by cristifalcas** [bazelbuild/rules_scala#1454]
When setting the `--nolegacy_external_runfiles` bazel flag, I get this error:

`/private/var/tmp/_bazel_cfalcas/856dc74a4318774eeb1496e4c7291b94/bazel-workers/worker-16-ProtoScalaPBRule/com_xxxx_search/bazel-out/darwin-opt-exec-38C78BB3/bin/external/io_bazel_rules_scala/src/scala/scripts/scalapb_worker.runfiles/com_xxxx_search/../io_bazel_rules_scala/src/scala/scripts/scalapb_worker_wrapper.sh: line 5: /private/var/tmp/_bazel_cfalcas/856dc74a4318774eeb1496e4c7291b94/bazel-workers/worker-16-ProtoScalaPBRule/com_xxxx_search/bazel-out/darwin-opt-exec-38C78BB3/bin/external/io_bazel_rules_scala/src/scala/scripts/scalapb_worker.runfiles/com_xxxx_search/external/remotejdk11_macos/bin/java: No such file or directory`

Based on the comment [here](https://bazelbuild.slack.com/archives/CA31HN1T3/p1669726932706059?thread_ts=1669723965.400059&cid=CA31HN1T3) it seems to because how `rules_scala` is trying to get the java binary:
```
So I think your rules_scala is looking up the Java binary inside the old runfiles symlink forest path.
scalapb_worker.runfiles/com_xxxx_search/external/remotejdk11_macos/bin/java

https://github.com/bazelbuild/rules_scala/blob/73f5d1a7da081c9f5160b9ed7ac745388af28e23/scala/private/rule_impls.bzl#L168-L169

Need to change it so that it look up the Java binary in a different path, probably something like:
scalapb_worker.runfiles/remotejdk11_macos/bin/java
```

**Comment by srdo** [comment]
Did you try the most recent code? We're using `--nolegacy_external_runfiles` and after https://github.com/bazelbuild/rules_scala/issues/1396 was fixed, it works fine for us.

**Comment by cristifalcas** [comment]
Yes, after upgrading our rules_scala, now the flag works!

Thank you and sorry for the noise
