### ISSUE TITLE
Same name resource files are overwritten by upstream deps

### ISSUE THREAD

**Issue by tanishiking** [bazelbuild/rules_scala#1455]
Reproduce example: https://github.com/tanishiking/bazel-playground/tree/main/13-bazel-resources

- We have 2 targets, `foo` and `base`.
- Both targets have a resource `a.txt`
- `foo` depending on `base`

```
.
|-- base
|   |-- BUILD
|   |-- base.scala
|   `-- resources
|       `-- a.txt
`-- foo
    |-- BUILD
    |-- foo.scala
    `-- resources
        `-- a.txt
```

```python
# base/BUILD
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")
scala_library(
    name = "base",
    srcs = ["base.scala"],
    resources = glob(["resources/**"]),
    visibility = ["//visibility:public"],
)

# foo/BUILD
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary")
scala_binary(
    name = "foo",
    srcs = ["foo.scala"],
    main_class = "foo.Foo",
    deps = ["//scala/base"],
    resources = glob(["resources/**"]),
)
```

```sh
❯ cat base/resources/a.txt
I'm from a.txt under base

❯ cat foo/resources/a.txt
I'm from a.txt under foo
```

## Problem
When we build `bazel build //scala/foo` the generated jar file contains one `a.txt` in jar, that's ok

```sh
❯ jar tf bazel-bin/scala/foo/foo.jar
META-INF/
META-INF/MANIFEST.MF
a.txt
foo/
foo/Foo$.class
foo/Foo.class
```

The problem is it's from `base`, instead of `foo`

```
❯ bazel-bin/scala/foo/foo
I'm from a.txt under base
```

It looks like the upstream resources are prioritized when the resource name crashes.

## Expectation
```
❯ bazel-bin/scala/foo/foo
I'm from a.txt under foo
```

Or is there a workaround for this?

**Comment by tanishiking** [comment]
Another example (comparing to sbt) with typesafe config https://github.com/tanishiking/typesafeconfig-sbt-bazel

**Comment by liucijus** [comment]
@tanishiking could you clarify what would be an expected behavior for you?

**Comment by tanishiking** [comment]
@liucijus Sorry, I was struggling to explain the expected behavior 😅 

Let's say we have targets `A` and `B` (where `A` depends on `B`), and both targets have the same name resource `a.txt`.
In this case, when we read `a.txt` from target `A`, we should read a resource `a.txt` **defined in A**.
However, it looks like we're reading `a.txt` defined in B instead.

(so, when the resource name crashes in A -> B, it looks like B wins. While I expect A to win).

**Comment by liucijus** [comment]
This looks like a bug, and probably happens [here](https://github.com/bazelbuild/rules_scala/blob/master/src/java/io/bazel/rulesscala/scalac/ScalacWorker.java#L65-L71). Fix should be as trivial as reordering those lines. @tanishiking, would you be interested in sending a PR with a fix and a related test?

**Comment by tanishiking** [comment]
Thank you for the pointer @liucijus Sure! I'll take a look probably later this week :)
