### ISSUE TITLE
WORKSPACE snippet should be io_bazel_rules_scala

### ISSUE THREAD

**Issue by sacsar** [bazelbuild/rules_scala#1468]
As far as I've been able to tell, the `WORKSPACE` snippet for 5.0.0 should be:
```
http_archive(
    name = "io_bazel_rules_scala",
    sha256 = "141a3919b37c80a846796f792dcf6ea7cd6e7b7ca4297603ca961cd22750c951",
    strip_prefix = "rules_scala-5.0.0",
    url = "https://github.com/bazelbuild/rules_scala/archive/refs/tags/v5.0.0.tar.gz",
)
```

(I as "as far as I've been able to tell" as I'm getting the cryptic `Analysis of target '.... failed; build aborted:` when trying to use `scala_proto_library`, but I'm working under the hypothesis I've messed that up. You can't configure the toolchains if you use `rules_scala` rather than `io_bazel_rules_scala`.)

**Comment by liucijus** [comment]
Thanks for reporting, @sacsar! Updated existing release with the correct name.
