### ISSUE TITLE
Getting decoding error after switching to 2.13

### ISSUE THREAD

**Issue by natansil** [bazelbuild/rules_scala#1470]
Hi,
when building [this](https://github.com/wix/greyhound/pull/540) branch (switched to Scala 2.13) I'm getting:

```
error: IO error while decoding 240 with UTF-8: 240 (No such file or directory)
Please try specifying another one using the -encoding option
```
Any idea what did I misconfigure? 
[Here](https://github.com/wix/greyhound/pull/540/files#diff-3e238222e7e9d6be9f7bf4c8aa8a7c9cc68b7bcd28bec4f0006dfc63fc9085d5) you can see my maven dependencies

**Comment by liucijus** [comment]
this was solved via private conversation
