### ISSUE TITLE
New dep tracking not working on Windows due to 'unused dep' errors 

### ISSUE THREAD

**Issue by crt-31** [bazelbuild/rules_scala#1487]
The new dep tracking developed in #1459 is not working on Windows, and is causing erroneous "unused dep" errors.

The issue is that in the patch files the "ArchivePath" variable has a windows path (with backslash '\\' instead of '/').  When the DepsTrackingReporter uses this to compare, it fails due to the slashes being different. 

Easy fix with a .replace('\\\\', '/'), but not sure if its best to put change in the DepsTrackingReporter or in each of the patch files. 
@liucijus can you advise?

**Comment by liucijus** [comment]
@crt-31, if patches are the only source of problem, maybe for Windows they can be fixed with [patch_cmds_win](https://bazel.build/rules/lib/repo/http#http_archive-patch_cmds_win)? I don't have environment to try this on, any help or contribution would be appreciated.
