### ISSUE TITLE
Investigate SCP-009 for warnings on over-broad deps.

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#149]
see: https://github.com/scala/scala/pull/5724

The idea is to add a flag to scalac that warns if a jar is on the classpath that is not used during compilation. With this, we could potentially make that a fatal error when given a certain flag (or of course using fatal warnings).

**Comment by softprops** [comment]
Very cool!

**Comment by ittaiz** [comment]
@johnynek should we close this in favor of #235 ?
It's more generic but it's also more indicative on the direction we're going (i.e. not to use the stock plugin but to use our own variant)

**Comment by johnynek** [comment]
yes, I think so.
