### ISSUE TITLE
Upgrade CI tests to use Bazel 6 

### ISSUE THREAD

**Issue by crt-31** [bazelbuild/rules_scala#1498]
Bazel has just released version 6.2.0, and has been on version 6 since Dec 2022.

The CI tests currently use version 5.3.1, but they should probably be modified to run some (or all?) of the tests using the latest LTS Bazel version which is 6.2.0.

_Note, I ran the tests with 6.0.0 on my local box, and ran into couple issues... mainly that the return value of str(label) has changed (see https://github.com/bazelbuild/bazel/issues/16196). This causes a few tests to fail... but should be straightforward to fix by not assuming output of str(label)._

**Comment by liucijus** [comment]
We don't run current tests on `6.x.x` because some *test* code is not compatible yet. I want to test a few fixes, and cut Rules Scala release, then I guess `.bazelversion` can be updated.

**Comment by crt-31** [comment]
OK, sounds good. I got all the tests working with 6.2.0 with a bunch of fixes... I'll post a PR once I get the CLA done.
