### ISSUE TITLE
SemanticdbInfo.plugin_jar should be File not string

### ISSUE THREAD

**Issue by aishfenton** [bazelbuild/rules_scala#1527]
`SemanticdbInfo.plugin_jar` currently returns a string of the jar path. Instead it should return a File object so that downstream users can use include it as part of their own rule outputs.

**Comment by crt-31** [comment]
assume you mean SemanticdbInfo.plugin_jar. Definately agree.
This should probably be fixed asap since this is part of a new public interface.

**Comment by aishfenton** [comment]
@crt-31 oops, yes, `plugin_jar`
