### ISSUE TITLE
Compiler diagnostics for scala 3 are missing.

### ISSUE THREAD

**Issue by ValdemarGr** [bazelbuild/rules_scala#1602]
The [current Scala 3 diagnostics reporter](https://github.com/bazelbuild/rules_scala/blob/master/src/java/io/bazel/rulesscala/scalac/reporter/PlaceholderForEmptyScala3Lib.java) looks like it is a noop. 

It looks like the scala 3 compiler has a `ConsoleReporter` [here](https://github.com/scala/scala3/blob/5101daf9f454c23898ec205894a1c97025f39515/compiler/src/dotty/tools/dotc/reporting/ConsoleReporter.scala#L13). Are there any obstacles for implementing it like the scala 2 variant?

**Comment by WojciechMazur** [comment]
I've started to work on that, but I cannot assign myself to the issue. 
I'm getting strange cyclic inheritance errors when  extending 'dotc.reporting.ConsoleReporter'. Might need to check if Scala compiler does not produce something strange in the byte code

**Comment by susliko** [comment]
@WojciechMazur I also was working on this today, haven't noticed your comment 😓 

Looks like I've got it working, but there are no tests yet.

It would be great to join efforts on this.
