### ISSUE TITLE
scala_repl takes common_attrs but never does any compilation

### ISSUE THREAD

**Issue by sdtwigg** [bazelbuild/rules_scala#180]
scala_repl takes common_attrs, which includes a bunch of stuff like srcs, deps, resources, etc. but only looks at deps and runtime_deps. There is no invocation of _lib or _scala_binary_common to actually compile the sources.

I can think of two paths I can think of depending on what do you think scala_repl should be:
1. scala_repl only takes deps and runtime_deps (where both are treated as runtime deps) as things to load into the resulting REPL environment.
2. scala_repl uses _scala_binary_common to actually do a compile of those sources similar to how scala_binary and scala_test can compile sources.

**Comment by johnynek** [comment]
it might be nice to have some scratch code to do some testing with, so option 2 might be nice. Although, you can also solve the problem with an additional library target.

**Comment by sdtwigg** [comment]
I'll try unifying with scala_binary_common.

It also would avoid having to change common_attrs while still allowing scala_repl to use it.
