### ISSUE TITLE
--strategy=Scalac=worker does not seem to place nicely with remote caching

### ISSUE THREAD

**Issue by softprops** [bazelbuild/rules_scala#196]
This may be a known thing not yet known to me, but something my time found in our travels was that after enabling the following in our bazel.rc file we noticed a sizable slow down on clean builds where we're trying to optimize our cache hit paths

```
build --strategy=Scalac=worker
test --strategy=Scalac=worker
``` 

Atm we're leveraging the `--spawn_strategy=remote --rest_cache_url=$BAZEL_REMOTE_CACHE` flags to cache build artifacts remotely.

I did a few timings of a clean build ( i.e. bazel clean then build  )
with the worker mode enabled

```
real    5m2.243s
user    0m27.712s
sys    0m2.658s
```

and without

```
real    2m2.171s
user    0m28.114s
sys    0m1.381s
```

My hypothesis is that there is some extra intelligence required that's currently missing from the scalac worker processor's implementation. I haven't dug too far into it yet but I wanted to report my initial findings here to see if others have run into the same issue.

Some initial thoughts. [WorkerProtocol](https://github.com/bazelbuild/rules_scala/blob/master/src/java/com/google/devtools/build/lib/WorkerProtocol.java) was generated 4 months ago and I realize remote caching been a moving target up until recently. That may play into this. Ultimately I think there may be some bazel "hooks" that aren't wired into the worker mode of scala rules just yet.

Alternatively it may a more common theme  that worker strategies are generally incompatible with remote caching. I haven't tested this with java libraries for comparison but our build is a bit too mixed with scala to test that atm.

**Comment by johnynek** [comment]
Cc @ianoc this is a known issue and maybe 0.5.0 will fix

**Comment by johnynek** [comment]
Can you try with 0.5.0rc and see if that fixes?

**Comment by softprops** [comment]
@johnynek to the rescue again! I dont know if Ill get to it this evening but I'll take note. If I can set up a test tomorrow I'll report back.

**Comment by ianoc** [comment]
The last i've heard from the goog folks was most of this is alpha and didn't work with standalone workers. But maybe it works in 0.5.x now... the remote stuff is under pretty active development at goog

**Comment by softprops** [comment]
> . the remote stuff is under pretty active development at goog

Yea I assumed as much. The [roadmap](https://bazel.build/roadmap.html) looks good. The remote caching via rest api has been working pretty well for us but we just ran into this little snag and wanted to forward the info along. We're also happy to jump in and help with patches if needed.

**Comment by softprops** [comment]
Wanted to report back on this with some early findings after doing some testing with this installer

```
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci/bazel--installer.sh
```

experiments are done with remote caching on and bazel cleans in between runs.

with worker enabled ( --strategy=Scalac=worker ) and the following ( bazel-wrapper installs bazel if its not installed on dev boxes and sets the remote cache args )

```
time ../tools/bazel-wrapper build \
  -s --verbose_explanations --explain explain.out --use_ijars --profile build.prof  \
  --progress_report_interval 1 \
  $(../tools/bazel-wrapper query "kind(scala_library, //...)")
```

```
real	5m53.066s
user	0m0.133s
sys	0m0.097s
```

with the same args removing the --strategy=Scalac=worker arg our build actually is still faster, faster then 0.4.5! ... but still slower with the worker :/ I don't expect this to get better with 0.5.0 but I think maybe it will be improved as the remote caching support matures

```
real	1m5.750s
user	0m0.095s
sys	0m0.080s
```

On a side note, the newer version added a neat little UX feature that adds the strategy in use next to "Running". 

```
 Running (worker):
        scala //chapstick:chapstick, 82 s
```

**Comment by softprops** [comment]
> On a side note, the newer version added a neat little UX feature that adds the strategy in use next to "Running".

Nope, I get this with 0.4.5 as well. I must have just now noticed it!

**Comment by ittaiz** [comment]
Why are you doing clean builds?

**Comment by ianoc** [comment]
Don't think I quite follow, there are i guess 3 states:

1) No cache settings without with workers enabled
2) Cache enabled with workers
3) Cache enabled without workers

And then for state:
1) Build locally what is a common state that would be in the cache from
clean
2) Build a leaf target having local + remote caches of everything else
3) Altering a central target and having a cascading set of targets needing
to be rebuilt

Which ones of these interactions do you benchmark for these? (Or I might
just be missing the point too)

**Comment by softprops** [comment]
To make it more clear my build is actually utilizing the remote cache. With the local cache in play it's harder to tell. We're trying to optimize for the case where an engineer (or CI machine) has executed  some work, other engineers won't have to, given the same inputs are at play

**Comment by ianoc** [comment]
My understanding is that any remote cache today doesn't work with local
workers, is that wrong? i.e. in the event of a cache miss it can't use the
local workers, it falls back to standalone mode.

**Comment by softprops** [comment]
> any remote cache today doesn't work with local
workers.

That I didn't know that.

I'm mainly following the cas cache docs [here](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md). 

I think the problem I'm seeing is that with the worker options _and_ the remote cache options. It's almost as if the remote cache is ignored. 

My guess now is that this combo isn't supported. 

What I'm going for is a distributed cache for outputs with what ever the fastest option is for compiling locally when an output isnt available. My assumption was that I could gain some speed with the scala worker when an output was not previously produced for the same inputs.

**Comment by ianoc** [comment]
Last I understood this was the case, from what I can tell from issues 0.5.0
hasn't fixed it (but I haven't tested it itself)

https://groups.google.com/forum/#!topic/bazel-discuss/GINp6C6tZ4I
https://github.com/bazelbuild/bazel/issues/2568
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/g4hwRbcRIRI/LDIeYuHaDgAJ

are the 3 bits of state that sort of capture what I've read/tried out.


The trade off currently is really sub-optimal from what I tried out a few
months ago -- If i used the remote cache I had to use a standalone mode,
but for an empty copy of master it could be much faster than doing any sort
of building. But as soon as I had to do any sort of non-trivial building of
the tree then the workers being faster than standalone became the dominant
factor. If you change branches a lot the remote cache can be better too
since local caching across branches doesn't keep that state for you. So
currently we use workers and no remote caching with the presumption that
users mostly incur the initial hit building more code but then can iterate
faster in their day. But not sure if/when its always really the right call.

**Comment by softprops** [comment]
Thanks for the extra context and links. I think that recipe would would a bit better for us after I do a bit more package surgery. We've got a handful of big modules that end up being our bottleneck. Sbt/Zinc did an okay job in only compiling what changed but because of the size of our modules and mixed java scala compilation,  analyzing that class graph took almost as much time as compiling. Not all engineers leave open sbt sessions so you have to pay a 30 second tax just to get in the door and do anything useful. Bazel is showing alot of promise for us so far but I'm still learning the rules of the road. The docs are great in most cases but lacking (maybe intentionally) for the feature I really want, distributed caching.

In my ideal build system units and actions would work like pure functions. If one person builds a unit the next person can just use that output because their input is the same. When it's a new input they can speedily compute it for the next person. So on and so forth.

**Comment by softprops** [comment]
Closing this as rules scala is working as designed bazelwise here.
