### ISSUE TITLE
bazel reporting test failures for passing tests

### ISSUE THREAD

**Issue by softprops** [bazelbuild/rules_scala#197]
we're experiencing an odd issue with bazel reporting tests as having failed even though they are passing . reporting the issue here in case others have experienced the same issue.

we run our tests as `scala_test` rules that map directly to our existing sbt's `src/test/scala/**.scala` globs. 

when I do a test run I see in the test logs ( scala test output I believe )

 ```
Tests: succeeded 104, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

but bazel reports

```
//base:test                                                              FAILED in 1 out of 2 in 6.2s
  /home/doug/.cache/bazel/_bazel_doug/9b83aa90a589949dfeac2b73a9d75602/execroot/modules/bazel-out/local-fastbuild/testlogs/base/test/test.log

Executed 1 out of 1 test: 1 fails locally.
```

**Comment by softprops** [comment]
update: I found that this problem goes away when I remove our remote cache args for testing. This makes me think there is some incompatibility and/or with test runs and caching in bazel core, not here. closing for now but as a breadcrumb trail for future engineers.

**Comment by ittaiz** [comment]
Doug,
Take a look at bazel itself, I seem to remember quite a lot of discussion
about remote execution and tests being an issue. I think some of all of it
was fixed in 0.5.0

**Comment by softprops** [comment]
beautiful, that release can't come fast enough!

**Comment by ittaiz** [comment]
If you can take bazel-HEAD for an evaluation spin that might help to
surface potential release blockers.

**Comment by softprops** [comment]
thanks for the tip @ittaiz. I tried the same full suite with remote caching enabled with the following installer

```
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci/bazel--installer.sh
```

Good news here! the `test` command seems to play much nicer with remote caching with the latest binaries. I'll look forward to 0.5.0

**Comment by softprops** [comment]
wanted to follow up since this is released now. works like a charm!

**Comment by johnynek** [comment]
Great! Doug, there is no improvement with 0.5.0 final and the caching OR
worker mode is there? That seems like such a non-starter we haven't been
messing with caching too much.

**Comment by ittaiz** [comment]
They are currently mutually exclusive

**Comment by softprops** [comment]
Remote cache for tests. Have it on but default but excluded for tests because of the weirdness mentioned above. 

@ittaiz is right. Worker and remote strategies are still at odds but that wasn't a blocker in this case. 

With remote caching on in 5.0,  tests in CI went from 8 minutes to just under a minute so that was a win!

**Comment by johnynek** [comment]
Can you detail this setup? This does sound interesting for CI.

**Comment by ittaiz** [comment]
This is, at least somewhat, proportional to the number of agents you have,
right? The less agents you have the higher the likelihood that the local
cache will have a hit.

**Comment by softprops** [comment]
With bazel we started with building in CI to compare with sbt then are rolling out to engineers. 

There's various pieces with CI and some of which are more interesting than others but here goes...

We run a containerized jenkins in k8s on gcp ( standard fare these days ). Jenkins jobs spawn k8s pods which volume mount our code and run a script inside the code, in this case a script that invokes bazel test with some extra args that we don't typically ask folks use `-s --verbose_explanations --explain explain.out --profile build.prof` ect, debug stuff.

We have an external cache for bazel outputs, the CAS blob outputs, also running in gcp. We tried to use the most basic nginx example but it didn't work at the time because of an http status code nginx returned didn't go over well with bazels success checks. So we wrote a small rustlang ( :D ) proxy pass to handle that. I think the status code thing may have been fixed in 5.0. It's on my todo list. That's backed by gcp network attached disk. We've found this faster and more reliable than google cloud storage buckets. 

Devboxes and CI share access to this remote bazel cache. So the picture my team is trying to paint is that if some where some one, or some robot built a bit of code or a package, you shouldn't have to rebuilt it if you're inputs are the same, which is probably _the_ selling point for bazel for us.

Our jenkins jobs set commit statuses on github pr commits. This usually indirectly gates merges so the business metric we're aiming for improve is faster turn around/feedback on whether or not a commit is safe to merge. We've seen a favorable impact here with bazel over sbt. On the flip side, this also benefits engineers because if jenkins runs the test there's less to build on devboxes. Thanks bazel!

One last piece we're still trying to figure out in CI is the code coverage story which is still a story being written with the ink still being wet in 5.0. I've learned a lot through experimentation with scoverage and scala rules but I haven't figured out all the pieces I'll be digging into that more in near future. I'll let you know what I find!

**Comment by ittaiz** [comment]
One last question if I may about your setup- do your Dev boxes also write
to the cache? If so do you have provisioning for them so as to make sure
they're the same env as CI?

**Comment by softprops** [comment]
Devboxes do write to the cache. As for env parity, roughly yes. Same java version ect, in that respect. 

I did have a bit of initial concern about how much the env affects cache keys but I received more clarity on that [here](https://github.com/bazelbuild/bazel/issues/2998)
