### ISSUE TITLE
remove scala_library _deploy.jar target

### ISSUE THREAD

**Issue by smparkes** [bazelbuild/rules_scala#21]
The scala_library `_deploy.jar` target has no equivalent meaning on the java side and is (probably?) unnecessary.

**Comment by smparkes** [comment]
Ah. I see why this is necessary at this point, since `java_`* can't depend on` scala_library` directly.

**Comment by johnynek** [comment]
but can't we solve that with #18 ?

**Comment by smparkes** [comment]
Solve the necessity? Yeah, should be able to.

I just meant I see why we can't remove this until there's some other way of depending on scala libs.

**Comment by johnynek** [comment]
still they are not "deploy_jars" as such because they don't have the transitive deps, right?

I wonder if fixing that is step 1.

**Comment by smparkes** [comment]
Do you mean _deploy.jars for scala_binary or scala_library? Yeah, getting _deploy.jar fixed for scala_binary would be great.

I don't know that getting _deploy.jar working for scala_library is all that useful since the need for those files is really just an artifact of not being able to rely on scala_librarys in java_librarys. They could be called anything and still fill that role. And I don't think in that case that the libraries should be flattened. That sounds dicey/like an antipattern. That's what exports are for, isn't it?

**Comment by johnynek** [comment]
this was made implicit (and as such optional) by #61 . It may go away in the future if bazelbuild/bazel#970 is fixed since the only reason they were kept now is to make exporting to java targets easier.
