### ISSUE TITLE
Filter tests with --test_filter

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/rules_scala#212]
Bazel allows filtering tests with [`--test_filter=`](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--test_filter), which passes the filter expression via the `TESTBRIDGE_TEST_ONLY` environment variable. [`DiscoveredTestSuite`](https://github.com/bazelbuild/rules_scala/blob/master/src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala) should filter tests with the `TESTBRIDGE_TEST_ONLY` variable to support the `--test_filter` argument.

**Comment by softprops** [comment]
may be a dup of #188

**Comment by johnynek** [comment]
seems easy enough to add. The previous ticket didn't actually get to noting the ENV VAR.

**Comment by softprops** [comment]
Yea I'm happy to jump on this is some isn't going to first.

**Comment by chaoren** [comment]
Ah yes, it's a dupe. I took a look at `DiscoveredTestSuite`, but it looks like it only supports class (test suite) level resolution, while `--test_filter` should work on the method (test case) level.

**Comment by ittaiz** [comment]
DiscoveredTestSuite didn't support method level for performance reasons. I
think if the env is there it should support it.
If you have any leads or want to jump in with a PR be my guest, otherwise I
think I'll get to it on Monday.

**Comment by ittaiz** [comment]
It seems that the title is similar but #188 is geared toward scala_test and This is geared towards JUnit and specs2.
Maybe we should leave it as is so @softprops can take #188 while either @chaoren or myself will take this one.
@chaoren, for general notice- what are the different formats of expressions test_filter usually brings with it?
Also, you say about that DiscoveredTestSuite seems to support test class filter only. Does test class filter work? Pretty sure that if such support exists it's by accident.

**Comment by chaoren** [comment]
@ittaiz 
> what are the different formats of expressions test_filter usually brings with it?

The [bazel docs](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--test_filter) don't have a strict specification for the flag, only this:

> The particular interpretation of filter-expression is up to the test framework responsible for running the test. It may be a glob, substring, or regexp.

but IntelliJ passes the following examples for Java:
```
--test_filter=com.example.firstTest#
--test_filter=com.example.firstTest#testMethod$
"--test_filter=com.example.firstTest#(testMethod1|testMethod2)$"
"--test_filter=com.example.firstTest#|com.example.secondTest#"
"--test_filter=com.example.firstTest#testMethod$|com.example.secondTest#testMethod$"
"--test_filter=com.example.firstTest#(testMethod1|testMethod2)$|com.example.secondTest#(testMethod1|testMethod2)$"
```

> Also, you say about that DiscoveredTestSuite seems to support test class filter only. Does test class filter work?

No, it doesn't work yet. I meant that if I were to implement it, I could just add a new filter [here](https://github.com/bazelbuild/rules_scala/blob/b776a218dc526f54043576762c2bc1790bf9755d/src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala#L72), but since it looks like the whole thing just returns a list of classes, there's no way to filter by method.

**Comment by chaoren** [comment]
It looks like for java rules, bazel just [formats the test names (class#method) and applies the java regex](https://github.com/bazelbuild/bazel/blob/master/src/java_tools/junitrunner/java/com/google/testing/junit/junit4/runner/RegExTestCaseFilter.java).
