### ISSUE TITLE
Should we delete/disable the "is_identical" test

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#217]
The test take a very long time to complete (~10 minutes IINM on travis) which causes flaky builds on travis. Additionally this test sometimes fails on my own machine (mac os) for an unclear reason which we have an issue for.
I just feel that the long feedback loop + travis flakiness is too much.
@johnynek wdyt?

**Comment by softprops** [comment]
I actually liked this an use it as the baseline for some other rule repos I've created. The reason being is that bazels claims on reproducibility is one of its core tenets.

**Comment by johnynek** [comment]
I don't want to give the test up either if we can avoid it. We can break
reproducibility in the rules by accidentally embedding timestamped or nonce
data. If we do that, we will destroy caching, so I think it is pretty
important to test.

**Comment by johnynek** [comment]
We don't run a test like this at Stripe, but since the scala rules are
creating a lot of important outputs, it seems like testing them makes a lot
of sense.

**Comment by softprops** [comment]
thats been an issue for is, mainly for srcjars. less so with binary jars.

**Comment by sdtwigg** [comment]
Perhaps we could move it to the end?

This should also speed things up a little since it wipes out the cache and
thus the targets after it are slower.

**Comment by softprops** [comment]
that makes sense to me and seems to address the faster feedback issue

**Comment by johnynek** [comment]
👍 

We should add a comment to keep it at the end. I think the problem is that it was at the end, but then we added tests.

**Comment by ittaiz** [comment]
Can we have two build configurations on travis? If so WDYT about separating it to a different build configuration? This way if we see flakiness we can judge if this is real or not. The problem is worsened by the fact that we run tests for 4 different configurations. A lot of times one of them times out on travis.

**Comment by ittaiz** [comment]
Have an idea-
Maybe we'll move this test to a different repo and have that defined as another travis check? I think this can help since it will minimize the scope of clean/rebuild

**Comment by ittaiz** [comment]
closing for now since the flakiness was solved. this is less of an issue now
