### ISSUE TITLE
support plugins on scala_library

### ISSUE THREAD

**Issue by smparkes** [bazelbuild/rules_scala#22]
The `scala_library` rule doesn't support the `plugins` attribute. Needed for things like the `auto-service` plugin which facilitates `ServiceLoader`s, e.g., to configure `logback`.

**Comment by johnynek** [comment]
can you give some links here? There are plugins for the scala compiler you mean?

**Comment by johnynek** [comment]
can't you use `scalaopts` https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L274

and pass `-Psomeplugin:opts`?

**Comment by smparkes** [comment]
http://bazel.io/docs/be/java.html#java_plugin
https://github.com/google/auto/tree/master/service

It's actually java annotation processing. And, yeah, scala and java have different concepts of annotation plugins.

In this particular case, I think it'd be possible to add a javac step to make things work though that won't work for other annotation processors / plugins.

I might be able to play with this in a couple of weeks ...

**Comment by johnynek** [comment]
from what I can see, those have to be applied with javac. I guess if you have the annotation in scope when you compile, scalac won't complain, then you need a step where javac is called on the resulting jar with the plugin and I guess a new jar is produced?

**Comment by smparkes** [comment]
Okay, I've looked into this a bit more. I created this issue before I really understood how JSR 269 annotation processing works.

It _is_ possible to do this, along the lines of what you mention: the only diff is you have to explode the jar and pass all the classes to `javac`, along with `-proc:only`, rather than pass in the intact jar.

But that seems like it's going too far. This isn't a bazel issue, it's a java vs. scala issue. And if we did this, it would only work for this one kind of annotation processing, since arbitrary JSR 269 annotation processors can do things that wouldn't work for this.

I think the right answer is to just create a native java class. In my case, I just extend a scala class, e.g.,

```java
@AutoService(Configurator.class)
public class JavaLogbackConfigurator extends LogbackConfigurator {}
```

This seems like a perfectly reasonable approach.

It's a little kludgy right now since we have to do the `java_import` trampoline to get scala libraries into java builds but there's another issue for that ...

**Comment by johnynek** [comment]
ok. So this adds to the need to solve #18
