### ISSUE TITLE
support neverlink

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#225]
Hi,
I've started to depend on `maven_jar`s via their own BUILD files in`third_party` and having a `scala_library` inside them. The reason I need `scala_library` and not `java_library` is because I need it to depend (runtime_deps) on some of my own targets AND because of https://github.com/bazelbuild/bazel/issues/3171 .
I need some of them to have a `neverlink` option and that isn't supported by rules_scala.
@ulfjack would appreciate any pointers you can spare.
cc @sdtwigg who touched this area if I'm not mistaken when working on the seams of java/scala

**Comment by sdtwigg** [comment]
I'm pretty sure the implementation is just this: https://github.com/sdtwigg/rules_scala/commit/478ce28166c376d9540f2ce4a1008e652bbee46a

It models how the native rules handle neverlink: (roughly) add to compile jars but not runtime jars.

Sorry, I did that last week but ran out of time to test it so didn't send it out.

**Comment by oscar-stripe** [comment]
isn't this a duplicate of #213

**Comment by ittaiz** [comment]
it is
