### ISSUE TITLE
Update documentation on which version of bazel is required

### ISSUE THREAD

**Issue by dseisun** [bazelbuild/rules_scala#233]
I was using bazel v .3.2 and was still getting `function "depset" not found errors` which threw me for a while. Not sure when that function was added to bazel but probably worth updating the documentation around that.

**Comment by johnynek** [comment]
It's actually a little hard to know exactly since we don't test on all
prior versions and bazel itself changes quite a bit from version to version.

This is why, by the way, we check bazel into most (but maybe not all) repos.

**Comment by ittaiz** [comment]
It should be easy in a week or two since we will probably require 0.5.2
(JavaProvider changes).

**Comment by johnynek** [comment]
We could just update the README each time we bump the travis version.

Actually, @dseisun you can find the gitsha you are using in the history then look at the bazel version we tested with in .travis.yml.

**Comment by ittaiz** [comment]
@dseisun we've started to update the `Getting started` section in the readme with the version like so:

> In order to use scala_library, scala_macro_library, and scala_binary, you must have bazel 0.5.3 or later and add the following to your WORKSPACE file:

Are we good?

**Comment by dseisun** [comment]
Works for me. Thanks
