### ISSUE TITLE
test_run.sh regression due to "service manifest" fix

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#272]
the e2e test added in #270 causes two regressions:
1. Major- if you run ./test-run.sh twice in a row the build fails on the "build_is_identical" test since the first hash includes the deploy jar (from the previous build) and the second one doesn't (since `bazel clean` cleans it and we don't explicitly request the deploy jar.
2. Minor- the test creates `service_manifest.txt` and doesn't clean after itself.
@johnynek I think 1 might be solvable by somehow excluding the deploy jar from the hash but maybe the better idea is to add building the deploy jar to both runs so we'll have the deploy jar covered in the "is_identical" part as well. WDYT? 
cc @azymnis

**Comment by azymnis** [comment]
@ittaiz oops, sorry about that

**Comment by azymnis** [comment]
@ittaiz should I pick this up given that I broke it?

**Comment by ittaiz** [comment]
You can and it would be very much appreciated but you don't have to.
My philosophy is that once we review and merge it's on us :)

**Comment by ittaiz** [comment]
Argyris,
Are you going to take it?

**Comment by azymnis** [comment]
@ittaiz sorry, I got a bit sidetracked. Sure, I'll pick it up

**Comment by ittaiz** [comment]
Awesome, thanks!
re `service_manifest.txt` you can see other examples of how we `rm` in a bash "finally" block
WDYT about the is identical issue?
Maybe it's better to exclude it from the comparison and later on if we'll want to add another very small deploy target to the test

**Comment by azymnis** [comment]
@ittaiz sgtm

**Comment by azymnis** [comment]
@ittaiz why not do a `bazel clean` before running `bazel build test/...` for the first time in `test_build_is_identical`? That would fix this, right?

**Comment by ittaiz** [comment]
yes but `test_build_is_identical` is already really slow, please let's not make it much slower.
I've been heavily developing rules_scala lately and because we strongly rely on slow e2es the feedback loop is problematic. I'd really like to not make the problem worse.

**Comment by azymnis** [comment]
@ittaiz got it, another solution is to just delete the deploy jar after I'm done with it, i'll just do that for now

**Comment by ittaiz** [comment]
ok. I think downside to that might be that bazel's cache will still think it's there. This is at least true to remote repositories.
I wonder how easy it is to just change this:
https://github.com/bazelbuild/rules_scala/blob/master/test_run.sh#L30
from ` bazel-bin/test/*.jar` to somehow "all jars without -deploy.jar"
