### ISSUE TITLE
`object of type 'File' has no field 'class_jar'.` error from intellij plugin when syncing scala targets

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/rules_scala#277]
I see this error in the Intellij Bazel console for every `scala_library` target in my project, during Sync:

```
ERROR: /REDACTED/common/BUILD.bazel:3:1: in @intellij_aspect//:intellij_info.bzl%intellij_info_aspect aspect on scala_library rule //REDACTED/common:common: 
Traceback (most recent call last):
	File "/REDACTED/common/BUILD.bazel", line 3
		@intellij_aspect//:intellij_info.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_kgessner/a607cbff8886d2ecb81399f157ed2535/external/intellij_aspect/intellij_info.bzl", line 18, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_kgessner/a607cbff8886d2ecb81399f157ed2535/external/intellij_aspect/intellij_info_impl.bzl", line 691, in intellij_info_aspect_impl
		collect_java_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "/private/var/tmp/_bazel_kgessner/a607cbff8886d2ecb81399f157ed2535/external/intellij_aspect/intellij_info_impl.bzl", line 386, in collect_java_info
		library_artifact(output)
	File "/private/var/tmp/_bazel_kgessner/a607cbff8886d2ecb81399f157ed2535/external/intellij_aspect/intellij_info_impl.bzl", line 130, in library_artifact
		java_output.class_jar
object of type 'File' has no field 'class_jar'.
```

It prevents intellij from analyzing the scala targets, and breaks most code analysis -- e.g. intellij can't find any of the imports.  The symptoms look like https://github.com/bazelbuild/intellij/issues/96, but I'm running versions of everything that should include those fixes:

- bazel version: 0.5.4-homebrew (I'm on OS X)
- rules_scala: 23d94aec640ebfdcf862d9dcc20ab14c4eb448c9
- intellij: IntelliJ IDEA 2017.2.4
- bazel for intellij plugin: 2017.08.29.0.2

I've traced the problem as far as the [`jars` value exported to intellij](https://github.com/bazelbuild/rules_scala/blob/23d94aec640ebfdcf862d9dcc20ab14c4eb448c9/scala/scala.bzl#L592) being incorrect -- it should be a list of structs like `[outputs]`, not a list of files.

I'll try to put together a small test project I can share.  Let me know if you need anything else, or if I should report this to bazelbuild/intellij instead.  Thanks!

**Comment by ittaiz** [comment]
Thanks! I've been investigating a different problem with the intellij plugin and I don't have the errors you're showing but it makes sense. I'll try to come up with a fix tomorrow and see how it effects my repo

**Comment by kevingessner** [comment]
Here's a small project that shows the error in intellij: https://github.com/kevingessner/scala-intellij-test --  let me know if that doesn't work for you.

@ittaiz I saw a different error with older versions of the plugin; something about `NoneType is not iterable`, IIRC.

**Comment by ittaiz** [comment]
Hi Kevin,
Haven't looked at the project but the error seems quite clear. My errors
are probably related to something else as I'm on a different commit of
rules scala.
I'll have a fix today or tomorrow out, ok?

**Comment by greggdonovan** [comment]
@ittaiz @kevingessner @brendandouglas  

How could we best go about setting up a sample `rules_scala` project like @kevingessner setup to run as an end-to-end test on changes to rules_scala, intellij, or bazel-deps?

I see [tests](https://github.com/bazelbuild/intellij/blob/master/scala/tests/integrationtests/com/google/idea/blaze/scala/sync/ScalaSyncTest.java#L71) of `scala_library` in the intellij plugin code, but I'm unsure how they work, as the intellij plugin doesn't import `rules_scala`.

**Comment by ittaiz** [comment]
Don't know, that's an interesting question.
I guess it's a question of how to do IntelliJ plugin tests right?
Once you have such a test we can setup another repo that depends on both.
If you're up for the challenge it can serve us I think

**Comment by brendandouglas** [comment]
We do have internal integration tests of our skylark aspect, including scala-specific tests. I haven't yet given any thought to open sourcing these, but it's something we'll eventually do.

We're also currently working on setting up end-to-end plugin sync tests, including bazel invocations (our current sync tests mock out the bazel invocations). This integration testing framework may not support external workspaces though.

**Comment by greggdonovan** [comment]
@brendandouglas End-to-end plugin sync tests sound like exactly what we need. By "external workspaces" do you mean projects in Git repos other than `bazelbuild/intellij`?

**Comment by brendandouglas** [comment]
By external workspaces, I mean bazel workspaces other than the primary one being tested (e.g. any external libraries referenced in the bazel WORKSPACE file).

**Comment by brendandouglas** [comment]
I've added some aspect tests to the IntelliJ GitHub project (https://github.com/bazelbuild/intellij/tree/master/aspect/testing/tests/src/com/google/idea/blaze/aspect/scala).

These scala tests are running against the old version of rules_scala we're using internally (and are currently broken when run against rules_scala HEAD).

**Comment by ittaiz** [comment]
Great!
Can you share why they're broken?
Kevin/Gregg,
Maybe we should open a new issue to articulate our game plan and get
feedback? And then you can continue with the PR like we talked?

**Comment by greggdonovan** [comment]
(_Sorry for the slow response._)

@brendandouglas Thanks for adding these! Should we be running anything other than `bazel test //aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/...`? I tried `bazel test 'scala/...'` but [couldn't get it to run locally](https://gist.github.com/greggdonovan/df01291133322c6597e17bbddd458e58).

@ittaiz @kevingessner -- In the notes for our meeting we had:

> In rules_scala’s travis: cloning the latest of intellij plugin, use override_repository to test intellij against proposed version of rules_scala.

So, something like `bazel --override_repository io_bazel_rules_scala=$(pwd)` in `./runTests.sh`? Does this still sound like a good plan?

**Comment by ittaiz** [comment]
Yes but I suggest a small change.
GitHub supports multiple checks per PR, can you check if Travis supports
having two different travis.yml?
This will separate the feedback of breaking rules scala itself to breaking
the integration with IntelliJ.
I wouldn't spend a day on getting it to work but if it's solvable in an
hour or two I think it's a better solution.

**Comment by greggdonovan** [comment]
Update:

Using the new aspect integration tests and [`git bisect`](https://gist.github.com/greggdonovan/7dcef8eaf809f01a97051ae0e88e51fa#file-git_bisect_test_intellij_aspect-sh) I see [this](https://github.com/bazelbuild/rules_scala/commit/1da7e63e5e8dcde77f422ac6017bc89977687ad0) as the commit that started to [break the aspect](https://gist.github.com/greggdonovan/7dcef8eaf809f01a97051ae0e88e51fa#file-rules_scala_aspect_failure_begins-txt).

However, the [failure with rules_scala master is different](https://gist.github.com/greggdonovan/7dcef8eaf809f01a97051ae0e88e51fa#file-rules_scala_master_fails_aspect-txt) and looks related to macros + ijars expectations. Any ideas?

**Comment by greggdonovan** [comment]
@ittaiz The idea would be to have a separate yaml for the IntelliJ integration tests so the current rules_scala travis.yaml CI could be green if only the aspect integration was broken? That makes sense.

A quick check for multiple `.travis.yaml` file support yields [this](https://github.com/travis-ci/travis-ci/issues/3540#issuecomment-124205227), unfortunately.

**Comment by ittaiz** [comment]
@greggdonovan 
Not sure but sounds reasonable that #278 fixed the first breakage.
From the bisect do you see any of other changes breaking the interface or is this from the intellij side?
I'll try to dive a bit into the stacktrace

And re multi travis.yml- let's drop it.
Any chance you can open a new issue about our plan (your original version) so people (mainly Oscar) can object or suggest better ways?

**Comment by ittaiz** [comment]
discussion should continue on #308
