### ISSUE TITLE
Scala 2.12: incremental compilation broken when worker is enabled

### ISSUE THREAD

**Issue by gkk-stripe** [bazelbuild/rules_scala#305]
Scala 2.12.3 (and earlier versions of 2.12) breaks bazel's incremental compilation when worker is enabled.
This was discovered and troubleshooted here: https://github.com/bazelbuild/rules_scala/pull/251#issuecomment-333246940

I'm creating this issue to keep track of it and to have a reference I can use in code comments.

The incremental compilation is broken due to a bug is in the scalac's classpath caching that can be disabled with `-YdisableFlatCpCaching` passed to the compiler. The scala/scala#6064 has a fix for the caching logic. It's not part of an official release, though. 2.12.4 is planned to be out very soon: https://github.com/scala/scala/milestones

I verified that the fix is working so we need to wait for the 2.12.4 release to have this fixed.

**Comment by ittaiz** [comment]
@gkk-stripe I remember you saying this issue still exists in 2.12.4, right? Preparing a new 2.12 cherry pick
