### ISSUE TITLE
how to configure compiler plugins?

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#31]
I am thinking that commonly, you might want a compiler plugin for the whole repo.

We might want to have something like `scala_library_internal` so then repos can make a local `scala_library` macro that sets up default compiler options.

That seems like it would work okay. Any better approach?

I don't know now namespacing works in skylark, but I assume I can't import a rule with a name `foo` and also define a rule with the same name (thus the work around of adding variants of `_internal` to all the rules so we can import just a few of those).

**Comment by jcoveney** [comment]
I feel like the "ideal" way to do it is exactly what you said skylark doesn't support... have the bazel people weighed in at all if they want to support any notion of namespaces for skylark functions?

**Comment by jcoveney** [comment]
So per the response in https://github.com/bazelbuild/bazel/issues/1158, it seems like you can rename imports. With that, you can do it the "ideal" way, I think?

**Comment by johnynek** [comment]
I think so. That's pretty good. We should probably just document that.

**Comment by johnynek** [comment]
Here is documentation of the scalacopts pattern:

https://github.com/bazelbuild/rules_scala/wiki/Setting-repo-wide-compilation-defaults

See #47 for compiler plugin support
