### ISSUE TITLE
scala_library deps uses ijar for scala_macro_library dependency

### ISSUE THREAD

**Issue by jjudd** [bazelbuild/rules_scala#333]
Hi everyone!

I'm trying out Bazel and the Scala rules and ran into something odd:

I have a `scala_library`, "foo", that depends on a `scala_macro_library`, "foo-macro". 

<img src="https://www.lucidchart.com/publicSegments/view/d20523f1-381f-4765-a00f-749be8de4b65/image.png" width="200">

When I build the `scala_macro_library`, it succeeds and the `bazel-bin/foo-macro` folder looks something like this

```
-r-xr-xr-x 1 james james 33274 Nov  7 19:40 foo-macro.jar
-r-xr-xr-x 1 james james    13 Nov  7 19:40 foo-macro_MANIFEST.MF
-r-xr-xr-x 1 james james  6347 Nov  7 19:40 foo-macro_worker_input
```

When I build the `scala_library`, it fails and the `bazel-bin/foo-macro` folder looks something like this

```
-r-xr-xr-x 1 james james 15214 Nov  7 19:41 foo-macro-ijar.jar
-r-xr-xr-x 1 james james 33274 Nov  7 19:40 foo-macro.jar
-r-xr-xr-x 1 james james    13 Nov  7 19:40 foo-macro_MANIFEST.MF
-r-xr-xr-x 1 james james  6347 Nov  7 19:40 foo-macro_worker_input
```

The `foo-macro-ijar.jar` file was created when building the `scala_library`. This causes the the build to fail because the library needs the jar, not the ijar, to compile with the macro.

If I copy the `foo-macro.jar` file out of the `bazel-bin/foo-macro` folder, add a `filegroup` and depend on the `filegroup` in the `scala_library` instead of the `scala_macro_library`, then the `scala_library` build succeeds.

```
filegroup(
    name = 'foo-macro-jar',
    srcs = ['foo-macro.jar'],
    visibility = ['//visibility:public']
)
```

I hope I'm missing something :), but I thought the purpose of the `scala_macro_library` was to not produce the ijar. If depending on a `scala_macro_library` in another build target produces the ijar, then how do I depend on a `scala_macro_library`?

My rules look something like this

```
scala_library(
  name = "foo",
  srcs = glob(["src/main/**/*.scala"]),
  visibility = ["//visibility:public"],
  plugins = ["@org_scalamacros_paradise_2_11_11//jar"],
  deps = [
    "//foo-macro",
    ...
  ]
)
```

```
scala_macro_library(
  name = "foo-macro",
  srcs = glob(["src/main/**/*.scala"]),
  visibility = ["//visibility:public"],
  plugins = ["@org_scalamacros_paradise_2_11_11//jar"]
  deps = [
    ...
  ]
)
```

I haven't created a small repro case yet (the issue is part of a bigger project), but can do so if that would help debug this issue.

**Comment by ittaiz** [comment]
Hi,
Thanks for the report!
I don't think you're missing anything and we might have broken something
though I find it weird none of our tests failed...
If you can attach a small repro here that would be great

**Comment by jjudd** [comment]
I bumped the rules_scala version I was using from 2191e5eb9a11c69e5d273977254e7cc99a692ba7 to 85308acbd316477f3072e033e7744debcba4f054 and things work again. Looks like I picked a borked version originally. My bad. 

I'll go ahead a close this.
