### ISSUE TITLE
Custom test runners (via @RunWith) are not supported together with a --test_filter

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/rules_scala#376]
Given a scala (junit) test:

```scala
@RunWith(classOf[MyCustomRunner])
class MyTest {
  @Test
  def myTest() = ...
}
```
```scala
public class MyCustomRunner extends BlockJUnit4ClassRunner {

    public static String mutableState;

    @Override
    protected List<TestRule> getTestRules(Object target) {
        mutableState = "Hello from test rules!"; // <--- this doesn't get executed from scala_junit_test
        return super.getTestRules(target);
    }
}
```

The code inside `MyCustomRunner` will not be executed, if `--test_filter` is passed.

Note that the same scenario works fine in a `java_test`.

**Comment by johnynek** [comment]
What if you use scala_library + java_test there? We could make a macro `scala_junit_test` or something that does this so we don’t need anything special for people that want something basic.
