### ISSUE TITLE
use scala_import for the scala sdk

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#379]
note we use java_import for the scala sdk jars:

https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L1051

this can have the effect of letting ijar hit macro jars as seen here:
https://github.com/johnynek/bazel-deps/pull/104

I think scala_import does not depend on the scala rules (it is really a "no-ijar-import" I guess). So we should be able to use that even for things in the sdk.

cc @ittaiz

**Comment by ittaiz** [comment]
Scala import will offer ijars but even then it will be optional so sounds
good

**Comment by liucijus** [comment]
Closing as it was solved at some time ago
