### ISSUE TITLE
extend scala_toolchain to include the scala-sdk

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#380]
we have a basic scala_toolchain now, but it does not include the scala version or the jars to use for the sdk (compiler, std-library, reflect, etc...)

It would be good to take a fresh look at the 2.12 branch and see what it would take to add all the differences to scala_toolchain so users can easily configure their toolchain.

We might want to include the jars for scalatest and/or specs as part of this eventually, but maybe for the first stab, get 2.11 and 2.12 usable with only toolchain config differences.

see #364

**Comment by ittaiz** [comment]
@johnynek this was done in #544 right or am I missing the intent here?

**Comment by johnynek** [comment]
Yeah I think this can be closed.
