### ISSUE TITLE
scala_proto_repositories uses bind incorrrectly

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#383]
@azymnis @johnynek 
I think `scala_proto_repositories` misuses bind (like I previously did with specs2) in the sense that if the graph changes when I upgrade a version I still need to bind the exact same full closure which is not the point.
I want to change it to only bind `scalapb` and `grpc` and have the default binding of it in this repo to be a scala_library/import which exports all of the current dependencies.
Any objections?

**Comment by johnynek** [comment]
no real objections.

I wonder if we should instead use a toolchain to configure the `scala_protobuf_toolchain` or something?

**Comment by azymnis** [comment]
@ittaiz @johnynek so this is an example of me just cargo culting stuff that I saw without really knowing what I'm doing. Please feel free to fix and show me how it should be properly done

**Comment by ittaiz** [comment]
That's what I thought thanks.
Now I'm deliberating about Oscar's proposal of a toolchain.
@or-shachar wdyt?

**Comment by ittaiz** [comment]
still relevant but I think we'll close this in favor of #403
