### ISSUE TITLE
scalac_jvm_flags not expanding locations like jvm_flags

### ISSUE THREAD

**Issue by nevillelyh** [bazelbuild/rules_scala#386]
I need to pass in a flag with path to a resource file at compile time, something like this:

```
scala_library(
    ...
    resources = "//path:file",
    scalac_jvm_flags = ["-Dresource=$(location //path:file)"],
)
```

This doesn't work and I got the following error:

`java.io.FileNotFoundException: $(location /path:file) (No such file or directory)`

Replacing `scalac_jvm_flags` with `jvm_flags` fixed the issue.

Looking at `scala.bzl` I noticed this under `def _write_launcher`
`jvm_flags = " ".join([ctx.expand_location(f, ctx.attr.data) for f in jvm_flags])`

But this under `def _compile`
`arguments=["--jvm_flag=%s" % flag for flag in ctx.attr.scalac_jvm_flags] + ["@" + argfile.path],`

So there might be some discrepancy in flag handling?

**Comment by nevillelyh** [comment]
I tried adding `expand_location` to the `scalac_jvm_flags` list comprehension but now it's complaining

`java.io.FileNotFoundException: ./file (No such file or directory)` (with `//:file`) so somehow the paths are relative?

**Comment by ittaiz** [comment]
Hi,
What is your original problem? What do you expect to read that flag? Is it a custom scala compiler plugin?

**Comment by nevillelyh** [comment]
Yes it's a custom macro that reads a file (JSON credential to an external service). I realized the relative path thing is by design and will work around it.

**Comment by ittaiz** [comment]
Sounds good.
Good luck!
