### ISSUE TITLE
rules_twirl and rules_play_routes

### ISSUE THREAD

**Issue by jjudd** [bazelbuild/rules_scala#419]
At Lucid we use the [Play Framework](https://www.playframework.com/) for our web services, so I wrote a couple Bazel rules to make it possible to use the Play Framework with Bazel: 
* [`rules_twirl`](https://github.com/lucidsoftware/rules_twirl)
* [`rules_play_routes`](https://github.com/lucidsoftware/rules_play_routes)

The rules have tests, a Travis build, Skydoc on GitHub pages that updates on build, and they run Skylint on build. We're not using them in production yet because we aren't using Bazel to build prod artifacts yet. However, we are using them for our dev Bazel build, so we have some (not all) devs using them.

I'm posting this here because I'm don't know if `rules_scala` has a Gitter, mailing list, Discord, or something to discuss things like this. If there is, please let me know and I'll move the discussion to there. If there isn't some place to discuss `rules_scala` stuff, would it be worth making one? I'm happy to help.

**Comment by ittaiz** [comment]
Thanks for the update and sorry for not commenting!
Oscar,
Wdyt about additional communication channels?
I’m not sure rules scala is big enough for its own channel apart from
bazel-discuss and SO.
I do however feel the need for a more chat based channel

**Comment by johnynek** [comment]
I would love to have a gitter channel. I think we have to set up a new repo because the bazel folks have ignored my 2-3 emails on the subject.

**Comment by ittaiz** [comment]
Why do we need a new repo? Not much of a gitter person

**Comment by johnynek** [comment]
gitter is attached to repos, by default, but maybe they have changed that, let me see.

**Comment by johnynek** [comment]
https://gitter.im/bazelbuild_rules_scala/Lobby

there we go, can you see that?
