### ISSUE TITLE
Upgrade protoc-jar (for FreeBSD support)

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_scala#421]
https://github.com/bazelbuild/rules_scala/blob/master/scala_proto/scala_proto.bzl#L15 uses 3.2.0, which isn't available for FreeBSD. [3.4.0 is](https://github.com/os72/protoc-jar/tree/master/bin/3.4.0).

**Comment by johnynek** [comment]
PRs gleefully accepted!

(this one you could probably even do from github's web-based editor).

**Comment by ittaiz** [comment]
fixed by #571 (upgraded to 3.6.0)
