### ISSUE TITLE
rules_scala + Bazel IntelliJ Plugin not breaking on breakpoints

### ISSUE THREAD

**Issue by jjudd** [bazelbuild/rules_scala#437]
We ran into an issue in which Bazel's IntelliJ Plugin and rules_scala does not seem to be hitting breakpoints set in IntelliJ.

From IntelliJ you can run the test and it passes.
<img src="https://i.imgur.com/Z3fAn5p.png">

When you set a breakpoint and debug the test, the breakpoint is never hit. This happens when running the test in debug mode from both the gutter and the "Run" menu.
<img src="https://i.imgur.com/Vep6A5h.png">

From the Bazel console output inside IntelliJ, it looks like it is setting up a debug port:
```
Listening for transport dt_socket at address: 5005
Connected to the target VM, address: 'localhost:5005', transport: 'socket'
```

It then runs the test and disconnects without ever stopping at the breakpoint
```
Disconnected from the target VM, address: 'localhost:5005', transport: 'socket'
Time: 0
```

I created a simple repro example here: https://github.com/lucidsoftware/rules_scala_intellij_debug_example

You should be able to import that entire repo into IntelliJ and repro the above. If anyone runs into issues reproducing this please let me know.

Curious if this is a known issue, if I'm doing something wrong, or if anyone has any thoughts on why this is happening.

Thanks for the help!

**Comment by ittaiz** [comment]
No idea since we’re not scala test users but I can tell you that this works
for (most) specs2 use-cases.
I’d suggest closing this one and opening one on the IntelliJ side

**Comment by jjudd** [comment]
Interesting. I created specs2 and scala test examples in that repo and neither of them worked.

I'll look into this more and open an issue with the IntelliJ side.

**Comment by ittaiz** [comment]
I didn’t actually tested your repo but just today I debugged a test which
seems identical to your specs2 example

**Comment by jjudd** [comment]
Very interesting. I wonder if it's something on our end.

**Comment by ittaiz** [comment]
Do you use your own fork of rules_scala? Latest plugin version I assume?
2017.3 IntelliJ?

**Comment by jjudd** [comment]
The example uses rules_scala master branch. I just updated it to the latest commit and it still doesn't hit the breakpoints. 

Bazel 0.11.1
Latest Bazel plugin
IntelliJ 2017.3.4
Ubuntu

I'm digging into it tonight. Hopefully I can find something. If not, I'll open an issue with the IntelliJ plugin repo.

Thanks for your help! It's good to know that it works for others.

**Comment by jjudd** [comment]
I updated my example and have some more info. I can hit some breakpoints, but not others.

In this test

```
class ExampleSpecs2Test extends SpecificationWithJUnit {
  def bar() = {
    1
  }

  "a specs2 test" should {
    "be debuggable in IntelliJ" in {
      val a = bar
      val b = 3
      val c = a + b
      println("specs2: statement 1")
      println("specs2: statement 2")
      println("specs2: statement 3")
      success
    }
  }
}```

I can set a breakpoint inside `bar` and it is hit. I cannot hit a breakpoint set inside the `"be debuggable in IntelliJ" in {` block. My hunch is that it has something to do with Scala's anonymous classes and functions.

I hooked the test up to `jdb` by doing `bazel test //src/test:ExampleSpecs2Test --java_debug` and then `jdb -attach 5005`.

I can set a breakpoint at `foo.ExampleSpecs2Test.bar()` and things stopped. To set a breakpoint for the test body, I have to set a breakpoint for `foo.ExampleSpecs2Test$$anonfun$1$$anonfun$apply$1.apply()`.

My guess is that `foo.ExampleSpecs2Test$$anonfun$1$$anonfun$apply$1.apply()` is somehow not working with the IntelliJ bazel plugin. I don't know of a good way to see what the IntelliJ debugger is doing under the hood.

I imagine that others should be able to reproduce this. If they cannot, maybe I'm missing some javac or scalc options.

**Comment by ittaiz** [comment]
James,
If you remove the “bar” call and put a breakpoint in one of the println
calls, does it stop?
Because the one case we see a problem with breakpoints is in specs2 tests
which have a “scope” and then they stop at the “scope” but not in the test
itself. If you inline the scope then the breakpoints work

**Comment by jjudd** [comment]
When I change the test to look like this
```
class ExampleSpecs2Test extends SpecificationWithJUnit {
  "a specs2 test" should {
    "be debuggable in IntelliJ" in {
      println("specs2: statement 1")
      println("specs2: statement 2")
      println("specs2: statement 3")
      success
    }
  }
}
```

I can set breakpoints on all of the println lines and it doesn't stop on any of them.

I can set breakpoints on `"a specs2 test" should` and `"be debuggable in IntelliJ" in {` and both of those are hit.

**Comment by jjudd** [comment]
This is looking like a Scala IntelliJ plugin issue. I've updated the project to support sbt, imported the project into IntelliJ using sbt, and I still can't hit the breakpoints. I'll file an issue over with Scala IntelliJ plugin.

**Comment by jjudd** [comment]
I'm getting a few people around the office to try importing it and seeing if they run into the same issue. 

I swear debugging specs2 tests like this used to work.

**Comment by jjudd** [comment]
It works for some people in the office and not others. Definitely not a rules_scala problem, but we're working on tracking down what the issue is :)

**Comment by ittaiz** [comment]
Yeah, I think a colleague also reproduced it with maven.
If you can write here the tracking issue over in scala IntelliJ it will
probably help others

**Comment by jjudd** [comment]
We've tracked down what versions work and which don't.

IntelliJ 2017.2 and the Scala plugin from the 2017.2 track hit the breakpoints using both Scala 2.11 and 2.12

IntelliJ 2017.3 and that Scala plugins on the 2017.3 track hit the breakpoints with only Scala 2.12.

**Comment by ittaiz** [comment]
Great!
We actually saw cases of the latter which don’t stop.
Did you open an issue yet?
If so we’ll try next week to add there a repro with2.12 /2017.3

**Comment by jjudd** [comment]
Issue has been filed: https://youtrack.jetbrains.com/issue/SCL-13461

**Comment by ittaiz** [comment]
@hmemcpy can you please update it with our ”Scope” use case?

**Comment by hmemcpy** [comment]
I added the comment about the `Scope` parameter to the issue on YouTrack, they are related. Seems that it causes breakpoint to.... break 😂

**Comment by ittaiz** [comment]
But James reported that even a simple test without Scope didn’t work. Were
you able to verify that on the simple case specs2 does stop?
If so I think it’s important to also report that since it might help triage
where things still work

**Comment by hmemcpy** [comment]
@ittaiz yes, it (where it == breakpoint in the test) didn't work for me when running with scala 2.11 (set in sbt) on the 2018.3 plugin. When I switched to Scala 2.12, I was able to place a breakpoint, but after adding `Scope`, it didn't work again.
So I believe those two issues are a) related b) not related to bazel

**Comment by ittaiz** [comment]
Thanks!

**Comment by jjudd** [comment]
I'm now able to hit these breakpoints in the latest version of the Scala plugin: 2017.3.15

**Comment by ittaiz** [comment]
Glad to hear. Should we close it?

**Comment by jjudd** [comment]
I'm double checking with people around the office that it is fixed for them. If it is, I will close the issue in just a bit.

**Comment by jjudd** [comment]
@hmemcpy had a comment on that issue. Does the update fix your use case as well?

**Comment by hmemcpy** [comment]
Thanks for the update! I'll check it first thing tomorrow and update!

**Comment by hmemcpy** [comment]
Hey @jjudd! I just checked, and can confirm that Scala plugin v2017.3.15 solves my issue as well! /cc @ittaiz 
Thanks for reporting it to JetBrains, I'll update there as well!
