### ISSUE TITLE
Scala worker's extractSourceJars is very slow

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/rules_scala#441]
I'm routinely seeing `extractSourceJars` taking 50+ seconds on not too large targets.

Quickly checking the source code suggests that this is fishy:

```java
InputStream is = jar.getInputStream(file); // get the input stream
      FileOutputStream fos = new FileOutputStream(f);
      while (is.available() > 0) {  // write contents of 'is' to 'fos'
        fos.write(is.read());
      }
```

 It looks like unbuffered i/o that's happening here.

**Comment by johnynek** [comment]
seems like an easy PR opportunity.

**Comment by johnynek** [comment]
closed by https://github.com/bazelbuild/rules_scala/pull/442
