### ISSUE TITLE
How can I add dependent libraries ? 

### ISSUE THREAD

**Issue by gravitywp** [bazelbuild/rules_scala#444]

**Comment by ittaiz** [comment]
What kind of dependent libraries?
Is this by any chance a more generic bazel question? If so it is more
suited for SO or bazel-discuss google group.

**Comment by gravitywp** [comment]
@ittaiz third party scala libraries like spark

**Comment by gravitywp** [comment]
I found bazel-deps project solved my problem.

**Comment by ittaiz** [comment]
Awesome!
Can you close the issue?

**Comment by gravitywp** [comment]
Sure, thanks for replying.
