### ISSUE TITLE
General scrooge performance

### ISSUE THREAD

**Issue by jcoveney** [bazelbuild/rules_scala#45]
Right now, the code generator is not as performant as it could be... of course, this is mainly with antipatterns (a ton of thrifts which depend on a ton of thrifts) that hopefully bazel will prevent, but which exist at many companies which heavily use thrift. There is a lot of work that could be done to make this maximally performant... some ideas
- Make scrooge imports jars https://github.com/bazelbuild/rules_scala/issues/44
- Use the full graph of srcjars/thrift jars to minimize the number of times we extract jars
- ??? (there are scrooge changes that could also probably better support this... such as keeping around some intermediate data or something, but at that point maybe we just want smaller targets...)

**Comment by johnynek** [comment]
I think most of these issues have been solved by: #143 and #137
