### ISSUE TITLE
ci.bazel.io build is broken

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_scala#49]
Broken by PR #29. See http://ci.bazel.io/job/rules_scala/105/

Linux (with sandboxing):
```
____From making thrift archive //test/src/main/scala/scala/test/twitter_scrooge/thrift:thrift:
external/local_jdk/bin/jar: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
external/local_jdk/bin/jar: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
ERROR: /home/ci/workspace/rules_scala/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/test/src/main/scala/scala/test/twitter_scrooge/thrift/BUILD:3:1: output 'test/src/main/scala/scala/test/twitter_scrooge/thrift/libthrift.jar' was not created.
ERROR: /home/ci/workspace/rules_scala/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/test/src/main/scala/scala/test/twitter_scrooge/thrift/BUILD:3:1: not all outputs were created.
ERROR: /home/ci/workspace/rules_scala/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/thrift3/BUILD:3:1: output 'test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/thrift3/libthrift3.jar' was not created.
ERROR: /home/ci/workspace/rules_scala/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/BUILD:3:1: output 'test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/libthrift2_a.jar' was not created.
```

OS X:
```
ERROR: /Users/ci/workspace/rules_scala/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/test/src/main/scala/scala/test/twitter_scrooge/BUILD:4:1: creating scrooge files //test/src/main/scala/scala/test/twitter_scrooge:scrooge1_srcjar failed: generator failed: error executing command 
  (cd /private/var/tmp/_bazel_ci/ac44d3454b4099e3ebd2d39821cf0e13/darwin-x86_64 && \
  exec env - \
  bazel-out/local-fastbuild/bin/src/scala/scripts/generator bazel-out/local-fastbuild/bin/test/src/main/scala/scala/test/twitter_scrooge/test/src/main/scala/scala/test/twitter_scrooge/libscrooge1_srcjar.srcjar_only_transitive_thrift_srcs bazel-out/local-fastbuild/bin/test/src/main/scala/scala/test/twitter_scrooge/test/src/main/scala/scala/test/twitter_scrooge/libscrooge1_srcjar.srcjar_immediate_thrift_srcs bazel-out/local-fastbuild/bin/test/src/main/scala/scala/test/twitter_scrooge/libscrooge1_srcjar.srcjar bazel-out/local-fastbuild/bin/test/src/main/scala/scala/test/twitter_scrooge/test/src/main/scala/scala/test/twitter_scrooge/libscrooge1_srcjar.srcjar_remote_jars): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
bazel-out/local-fastbuild/bin/src/scala/scripts/generator: line 3: bazel-out/local-fastbuild/bin/src/scala/scripts/generator.runfiles/external/local_jdk/bin/java: No such file or directory
```

**Comment by johnynek** [comment]
@damienmg I think this came from removing `jdk` but what confuses me is that we are not explicitly using it. We are using `jar` and a bazel rule that itself depends on `jdk`.

Is seems strange that depending on `jar` alone is not enough (shouldn't it declare its dependendency on jdk?) and a rule that depends on something that depends on `jdk` (i guess the OSX error) shouldn't also be needed right? Otherwise users need to add the transitive deps, which seems wrong to me.

**Comment by johnynek** [comment]
okay, this is an issue with `0.2.1` vs `0.2.2`. The runfiles path changed to include the workspace name in `0.2.2`. I'll fix this for `0.2.2` head when the homebrew rule ships, until then I assume a good group of people are still on `0.2.1` (including our devs at Stripe).

**Comment by johnynek** [comment]
PS: I installed a VM with linux to test this, so I am fairly confident that I can repro the failures now. It would be great if we had a CI on the PRs so we didn't need to rely on this or pings from you, but I know I have mentioned that before.

In this case, bazel really changed between minor releases, so I don't see how we could have been correct without branches.

**Comment by damienmg** [comment]
So the Linux error is because we cannot create executable filegroup with multiple files. So jar is a filegroup that point to the jar binary but the jar binary still requires some other library. On Linux we sandbox and undeclared dependencies doesn't get mounted in the sandbox, therefore the error.

The workspace name issue got fixed on version 0.2.2 (it got broken with load statement in the workspace file). Unfortunately, we have another problem and it is not yet merged in Homebrew (for a different reason).

@kchodorow have proposed a patch to TensorFlow Serving for making their use case works on both version.

I am still working on vetting PR. I have to cut the Bazel job in two for that and it's breaking currently because we have ourself an incompatible change. Sorry for that taking so long.

**Comment by damienmg** [comment]
fyi we have deactivated the test until this bug is fixed. I have a fix for homebrew so I probably do a new release in the following days

**Comment by johnynek** [comment]
Okay. Sorry about dragging on this. After the new release I'll try to add a
Travis CI build for multiple versions of Bazel so we don't have this issue
in the future.

On Wednesday, May 4, 2016, Damien Martin-Guillerez <notifications@github.com>
wrote:

> fyi we have deactivated the test until this bug is fixed. I have a fix for
> homebrew so I probably do a new release in the following days
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/rules_scala/issues/49#issuecomment-216891748>
>


-- 
P. Oscar Boykin, Ph.D. | http://twitter.com/posco | http://pobox.com/~boykin

**Comment by damienmg** [comment]
No problem, after the new release I should be able to activate PR vetting
(it's blocked because someone introduced yet another incompatibility in
Bazel, so we cannot build bazel with 0.2.2 either...).

**Comment by johnynek** [comment]
@damienmg should be fixed by #54 would be great to get added to CI again.

(I checked our tests on my linux vmware install, which passed).

**Comment by johnynek** [comment]
@damienmg can you close this when you re-add us to CI?

**Comment by damienmg** [comment]
Sure I am doing that right now :)

**Comment by damienmg** [comment]
And it is green and you have PR vetting now.

You should accept the invitation to the bazelbuild org and make it visible so you can trigger yourself the builds :)
