### ISSUE TITLE
Travis CI test has been disabled

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#493]
I just noticed that Travis has been disabled it seems and has not run for the past several runs.

So, our additional shell driven tests have not run. This is not good. We had a lot of tests that we didn’t know how to put into bazel.

Cc @ittaiz @andyscott

**Comment by andyscott** [comment]
There's not a whole lot I can do to debug this; you have to be a maintainer/collaborator to manage the Travis CI settings (for anything past the yaml file in the repo).

**Comment by johnynek** [comment]
I assume a googler disabled it and didn’t bother to mention to us. I am not an admin I only have write access.

**Comment by johnynek** [comment]
I see two paths here:

1. Contact a googler admin who can re-enable travis
2. Port all our CI tests the buildkite.

**Comment by andyscott** [comment]
Gah, that's unfortunate on both fronts!

**Comment by ittaiz** [comment]
Arghhh,
I actually saw it’s disabled but was sure I was seeing it wrong...
@philwo can you please help us and re-enable Travis?
We should move our tests inside of bazel but that will take effort

**Comment by ittaiz** [comment]
I’m away from keyboard.
Can one if you run the test at least against your current bazel version on Mac and Linux to see how much of a problem we have?

**Comment by philwo** [comment]
I can fix your Travis setup in this repo if you tell me what buttons to click and what fields to fill in with which data. We don't have a shared Travis CI account for bazelbuild projects, but if you set something up for this repo, I can surely add any required webhooks and integrations.

We didn't disable any webhook (though in case this ever happens without asking you before, it would be by accident - we do ask before making such changes and have done so in the past, e.g. https://github.com/bazelbuild/rules_nodejs/issues/87).

Here's how the Travis CI integration is currently setup:
<img width="1011" alt="screen shot 2018-05-05 at 19 03 18" src="https://user-images.githubusercontent.com/504652/39665596-54171f94-5097-11e8-8f0e-107afacb5f25.png">
<img width="1020" alt="screen shot 2018-05-05 at 19 03 24" src="https://user-images.githubusercontent.com/504652/39665601-59828338-5097-11e8-91e7-ea02da00fec4.png">

Maybe @damienmg knows, considering his username shows up in the settings?

**Comment by philwo** [comment]
It looks like I might have been able to fix this :) I logged into Travis CI with my GitHub account and saw the rules_scala repo with a disabled switch. I enabled the switch and this modified the above seen Travis settings to look like this:

<img width="750" alt="screen shot 2018-05-05 at 19 41 42" src="https://user-images.githubusercontent.com/504652/39665955-5f325e16-509c-11e8-83b0-079086ae70d6.png">

**Comment by ittaiz** [comment]
Yay! Thanks!
