### ISSUE TITLE
aspect based proto rules

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#548]
similar to #524 do the same for proto rules to fix the same issues.

**Comment by ittaiz** [comment]
What problems exactly? Because proto doesn't use the `extra_information` it just uses the transitive proto sources from the proto provider

**Comment by johnynek** [comment]
I think that currently the proto rules rebuild the transitive closure of all protos on each invocation.

That is not what you want. It means unless you make sure you have no overlaps (your proto_library forms a tree, not a DAG), you will duplicate class files in the jars across targets.

**Comment by johnynek** [comment]
actually, it does not look like it has that bug, but you do need to manually build the graph correctly.

The aspect approach automatically generates a 1 for 1 proto_library to action DAG.

**Comment by simuons** [comment]
@ittaiz I think this issue can be closed

**Comment by ittaiz** [comment]
Thanks!
