### ISSUE TITLE
Exclude jars from deployables

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/rules_scala#560]
We have some maven projects that use maven-assembly and maven-shade plugins to produce a fat jar with some modifications. I was recently working on performing those with bazel, and it turned out that the SingleJar utility already supported most of the scenarios we need. So a combination of producing a deployable.jar + [jar_jar](https://github.com/johnynek/bazel_jar_jar/) can get us very far.

The only thing that is missing is the ability to filter our (exclude) certain jars from being included in the deployable.

To make things easier, I propose adding an additional parameter to `scala_library`, called `exclude_for_deployment` (or similar), which would accept a list of targets to exclude. Those targets will not be included in the final deployable.jar, and everything will "just work".

@johnynek WDYT?
@ittaiz

**Comment by ittaiz** [comment]
Discussion continues on 1402 issue of bazel itself.
Essentially what we need is provided scope but our current suggestion is an
intermediate step to have provided only for deploy jars

**Comment by hmemcpy** [comment]
Closing in favor of #576
