### ISSUE TITLE
scala.reflect.internal.MissingRequirementError

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_scala#591]
Building with Bazel 0.16.1, I get

`error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.`

I use the following code to compile:

```
package db

object Login {

    val graph = RunnableGraph.fromGraph(GraphDSL.create() { implicit builder: GraphDSL.Builder[NotUsed] =>
        import GraphDSL.Implicits._

        val database = Sink()

        val out = Sink[SessionData]()

        val announceLogin: SourceShape[LoginCommand]
        val sendLoginData: Flow[LoginCommand.UserData, LoginResponse]

        announceLogin -> database -> sendLoginData -> database -> out

        SourceShape(out)
    })
}
```

I do know that imports are missing. The error message is still unhelpful to say the least.

**Comment by jjudd** [comment]
Scala version needs to be JDK 9 compatible. Bazel 0.16 moved to using JDK 9. Are you using 2.11.12 or 2.12.6?

**Comment by abergmeier** [comment]
> Bazel 0.16 moved to using JDK 9

Hasn't that been reverted for 0.16.1?

> Are you using 2.11.12 or 2.12.4 or greater?

Only default, which makes it `2.11.12`, I think.

**Comment by ittaiz** [comment]
Can you for completeness paste the error you used to get (if any)?
I’m just used to useless error messages from scalac so want to focus on the
diff

**Comment by abergmeier** [comment]
Ok, using a89d44f7ef67d93dedfc9888630f48d7723516f7 made it work again. Perhaps change the docs to include a default which works with 0.16.1.
