### ISSUE TITLE
/bin/bash does not exist on certain systems

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/rules_scala#595]
Some [bash scripts within rules_scala][rules_scala] and the java launcher generated using [`java_stub_template`][java_stub] pulled in [here][dl_stub] refer to `/bin/bash` in their shebang.

This path does not exist on all systems in particular on [NixOS](https://nixos.org/) where the issue was discovered. This causes failure of generated test runners. E.g. Running `bazel test //example-lib:test` on this [Bazel Scala example][bazel-scala-example] raises an error stating `/bin/bash: bad interpreter: No such file or directory`.

Replacing `/bin/bash` by `/usr/bin/env bash` resolves the issue (tested locally). A corresponding PR on bazel will be opened shortly. The patch to rules_scala will depend on this first PR being accepted in bazel.

  [rules_scala]: https://github.com/bazelbuild/rules_scala/search?p=2&q=bash&unscoped_q=bash
  [java_stub]: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt
  [dl_stub]: https://github.com/bazelbuild/rules_scala/blob/9801202b2c82f6ad7da85b014a84f9354853f479/scala/scala.bzl#L364-L379
  [bazel-scala-example]: https://github.com/avibryant/bazel-scala-example

**Comment by rightfold** [comment]
The output of scala_binary still uses /bin/bash in the generated scripts but I don't know if this is a problem with the built-in Bazel Java rules or rules_scala.

**Comment by johnynek** [comment]
We use the same launcher script as bazel does. It should be fixed in bazel and when it is we can point to it.

Probably we should write a C or C++ launcher and build that with bazel to make things hermetic.
