### ISSUE TITLE
Force compressed output jar

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/rules_scala#598]
Seems that the SingleJar utility supports the `--compression` flag.
We have an internal rule that is using the SingleJar utility to produce an uber-jar, and without the `--compression` flag, it is about twice the size it ought to be.

Any reason not to do this by default in the `_build_deployable` rule?

**Comment by johnynek** [comment]
I don't think there is a reason not to do this unless the compression slows us way down, which I assume it won't.

It may really improve perf since we do less IO, especially with caching.

**Comment by ittaiz** [comment]
@hmemcpy,
Can you send the PR?
