### ISSUE TITLE
lint.sh is not working

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#602]
lint.sh seems to work differently, which suggests it is floating on a branch name and not reproducible.

Or at least, I can't run the script anymore locally and my branch currently fails.

See #601 for an example failure.

**Comment by johnynek** [comment]
this tool was added in #489 

@andyscott would you have any cycles to take a look?

**Comment by andyscott** [comment]
I can take a look today

**Comment by liucijus** [comment]
We have lint enabled in CI for some time, seems to be functioning without problems
