### ISSUE TITLE
an unexpected/undocumented dependency on errorprone

### ISSUE THREAD

**Issue by softprops** [bazelbuild/rules_scala#618]
I'm in the process of migrating a repo ( second attempt ) to the latest version of bazel, 0.17.2, and the tip of rules_scala. Something I this discovered in the process was new compile time errors not due to syntactic but due to static code analysis phase provided by errorprone. I didn't seem this dependency documented anywhere or how to opt out of it, I'm wondering if the hard dependency on it was intentional or not. In either case it would be good to have it documented and how to accommodate it.

**Comment by johnynek** [comment]
I don't know what `errorprone` is.

Is this something in the rules? Have I misunderstood your comment? Do you have any links?

**Comment by softprops** [comment]
Spotted a few refs here https://github.com/bazelbuild/rules_scala/search?utf8=✓&q=errorprone&type=. It's very cool!.. but unexpected and is causing us some upgrade friction. It's a google tool  that detect common programmer errors and turns them into compiler errors. I was looking for a way to opt out but I could not find a way

**Comment by softprops** [comment]
Now seeing these are comments I think the source may be in the latest release of bazel. We're upgrading to 0.17.2

**Comment by softprops** [comment]
Yep I'm spotting a bunch of refs to this in bazel proper. It's likely Scala rules is just inheriting support https://github.com/bazelbuild/bazel/issues?utf8=✓&q=is%3Aissue+is%3Aopen+errorprone I'll dig though the changelogs. We're coming from 0.6.1

**Comment by ittaiz** [comment]
I think this is just thanks/due to us using java_common.compile and Bazel
turning this on by default.
We internally use:
default_java_toolchain and in the misc attribute we pass
"-XepDisableAllChecks" which disables error prone

**Comment by softprops** [comment]
Thanks @ittaiz so far the errorprone thing has done more good than harm. Everything it's found was a legit bug in our code base! What I was looking for here was more documentation that it existed ( because it was surprising not because it was bad ) and potentially documentation in the readme on how to control it. Now that it's found this many bugs I'm kind of happy with it :) I was just looking for more documentation on where it came from. It was kind of mysterious to me :)

**Comment by ittaiz** [comment]
Maybe you can add a line to our readme explaining we use java rules under
the hood so people should expect its features
(default_java_toolchain/errorprone/etc)?

**Comment by softprops** [comment]
what's the equiv `load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")` that I need to load from in order to bring `default_java_toolchain` into scope of my WORKSPACE file

**Comment by softprops** [comment]
I kind of figured that part out but it seems I can't load this from a WORKSPACE file

```python
load("@bazel_tools//tools/jdk:default_java_toolchain.bzl", "default_java_toolchain")
default_java_toolchain(
    name = "your_default_java_toolchain8",
    bootclasspath = ["@bazel_tools//tools/jdk:platformclasspath8.jar"],
    javac = ["@bazel_tools//third_party/java/jdk/langtools:javac_jar"],
    jvm_opts = ["-Xbootclasspath/p:$(location @bazel_tools//third_party/java/jdk/langtools:javac_jar)"],
    misc = [
    "-g",
    "-deprecation",
    "-XepDisableAllChecks",
    ],
    source_version = "8",
    target_version = "8",
    visibility = ["//visibility:public"],
)
```

```bash
ERROR: /usr/local/git_repo/meetup/modules/WORKSPACE:4:1: Traceback (most recent call last):
	File "/usr/local/git_repo/meetup/modules/WORKSPACE", line 4
		default_java_toolchain(name = "your_default_java_toolch...", <7 more arguments>)
	File "/home/doug/.cache/bazel/_bazel_doug/9b83aa90a589949dfeac2b73a9d75602/external/bazel_tools/tools/jdk/default_java_toolchain.bzl", line 84, in default_java_toolchain
		native.java_toolchain(name = name, **toolchain_args)
java_toolchain cannot be in the WORKSPACE file (used by //external:your_default_java_toolchain8)
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'scala/toolchains.bzl': no such package '@io_bazel_rules_scala//scala': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'scala/toolchains.bzl': no such package '@io_bazel_rules_scala//scala': error loading package 'external': Could not load //external package
```

**Comment by softprops** [comment]
If this doesn't go into WORKSPACE, would this go into a BUILD file. we have a lot of BUILD which makes that a little cumbersome.

**Comment by ittaiz** [comment]
This goes into a BUILD file (any BUILD file, just one) and then the RC uses
that label
