### ISSUE TITLE
deprecated `jvm_flags` not reflected in `scala_library_suite` or `scala_test_suite`

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/rules_scala#621]
The README marks the `jvm_flags` attribute to `scala_library` and `scala_test` as deprecated. But, the corresponding `scala_library_suite` and `scala_test_suite` macros don't reflect this deprecation, as they only accept the `jvm_flags` attribute.

**Comment by ittaiz** [comment]
Isn’t there a kwargs there? Don’t remember and AFK

**Comment by aherrmann** [comment]
@ittaiz No, e.g. passing `scalac_jvm_flags` to `scala_library_suite` causes the following error:

```
unexpected keyword 'scalac_jvm_flags' in call to scala_library_suite
```

However, passing that attribute to `scala_library` does not cause an error.

**Comment by ittaiz** [comment]
We don’t use these utilities and I guess @johnynek on the other hand does
use the flag so it fell between the cracks.
@johnynek any objections to propagating a kwargs dictionary?
We often do this in internal macros

**Comment by aherrmann** [comment]
The `plugins` attribute is not passed on either. A `kwargs` dict seems like a good way to cover all these.

**Comment by johnynek** [comment]
I think it was just an oversight that we didn’t plumb them through. A PR with a test would be great.
