### ISSUE TITLE
objects not always discovered by scala_test rule

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#637]
a test like:

```
object Foo extends FunSuite {
  test("foo") { assert(false) }
}
```

Seems to silently look like a passed test as no suites are discovered.

Changing to `class Foo extends FunSuite` seems to fix.

I don't know if this is a bug with scala-test or rules scala or a combination.

I think we should probably error when someone makes a test that has no discovered suites. It might help people catch issues like this.

**Comment by ittaiz** [comment]
We error in junit discovery in such a case so I definitely agree

**Comment by johnynek** [comment]
yeah, and also munit has this behavior if I'm not mistaken. I just never use this pattern anymore.

I think we can close this.
