### ISSUE TITLE
'Unused dependency checking' is causing failures in rules_scala/test build

### ISSUE THREAD

**Issue by majcherm-da** [bazelbuild/rules_scala#642]
![scala_rules_unused_deps](https://user-images.githubusercontent.com/43614029/48721645-a66cee00-ec22-11e8-9777-8e509a8c09e8.PNG)

To reproduce run:

    bazel test //test:HelloLibTest

in `rules_scala` / `test`s

**Comment by johnynek** [comment]
@majcherm-da thanks for the bug report. That plugin is not totally perfect. We have seen some cases where it errors saying something is unused, but if removed, it does not compile.

For those targets, we disable the checker on the target currently.

cc @andyscott @beala-stripe maybe Stripe can prioritize taking a stab at improving this, but so far we have been working around.

An idea outcome would be getting this a supported flow in scalac, but so far, we have not had a ton of luck advocating for that. @stuhood had a proposal for scalacenter related to this, but I can't find it now, and I don't think it has moved forward. Unfortunately, as far as I can tell, lightbend, scala center and EPFL are putting close to zero effort on the large build problem (the domain of bazel, pants, buck).

**Comment by majcherm-da** [comment]
I created a PR to fix this problem. It's specifically a Windows related issue: https://github.com/bazelbuild/rules_scala/pull/717

**Comment by liucijus** [comment]
Solved in #717
