### ISSUE TITLE
strange behavior with scala_import_external and and neverlink=1

### ISSUE THREAD

**Issue by dmead** [bazelbuild/rules_scala#648]
Hi guys

I've got an assembly jar that my project depends on. In sbt land it was fine to use "Provided" to satisfy the build, but in bazel obviously this becomes neverlink.

I noticed that in the call to `scala_import_external` i can set `neverlink = 0` and it's fine

However, if i set `neverlink = 1` the errors make no sense.

``` expected value of type 'int' for attribute 'neverlink' in 'scala_import' rule, but got True (bool) ```

Does this make no sense to anyone else?

I'm on this version of rules_scala

```https://github.com/bazelbuild/rules_scala/archive/0eab80ff0696d419aa54c2ab4b847ce9bdcbb379.tar.gz```

**Comment by johnynek** [comment]
What version of bazel are you running with?

Could you send a PR with a test that fails replicating the issue?

**Comment by ittaiz** [comment]
Can you try with True/False?
I think we already had an int there but found out that in java_import they
use a bool.
@anchlovi you were the one orchestrating this, do you remember something
else?

**Comment by dmead** [comment]
this is bazel 0.18. I can have a small demo of the problem up later today or tomorrow. Though it should be pretty obviously a type mismatch (I'm assuming).

 I make a call like this


```
scala_import_external(
  name = "some-assembly-jar", 
  neverlink = 0,
  licenses = ["notice"],
  jar_urls = ["some-http-url"],
  jar_sha256 = "that-jar's-sha",
)
```

these are my results with all the reasonable values for neverlink

- `neverlink = 0` 
  - no errors

- `neverlink = 1 `
  - `expected value of type 'int' for attribute 'neverlink' in 'scala_import' rule, but goTrue (bool)`

- `neverlink = True `
  - `expected value of type 'int' for attribute 'neverlink' in 'scala_import' rule, but got True (bool)`

- `neverlink = False`
  - `no errors.`

**Comment by ittaiz** [comment]
upgrade your commit. This was fixed end of September.
https://github.com/bazelbuild/rules_scala/commit/f33c6a659e3af540de35df1413f57f31d36d70c7#diff-e749cc914badf2070de91ba97e1b8819

**Comment by dmead** [comment]
thanks very much!
