### ISSUE TITLE
Feature: avoid external lib source-jar downloading based on build environment

### ISSUE THREAD

**Issue by sha1n** [bazelbuild/rules_scala#652]
We (Wix) want to introduce a feature that allows us to spare source-jars fetching for external libraries (imported using `scala_maven_import_external`) on specific build environments, regardless of the static value specified with `fetch_sources`. 
I already have a working example of an environment variable based implementation, which seems to be suitable for our requirements. Before I take this forward, I would like to collect feedbacks and see whether this feature interests anyone outside of Wix, and if it does, I would like to discuss details such as where do we implement it and what method do we use and take it from there.

It's worth mentioning here that the `scala_maven_import_external` implementation is completely detached from [jvm_maven_import_external](https://github.com/bazelbuild/bazel/blob/49b7d05c9d51371936616548a181f1cf12e95323/tools/build_defs/repo/jvm.bzl#L212) that's built into Bazel.

Any thoughts or suggestions?

**Comment by ittaiz** [comment]
I'll just add that the fact that the implementation is detached is my fault
and I will make sure this is aligned in the next few months.
