### ISSUE TITLE
ScalaPB behavioral differences during migration from SBT

### ISSUE THREAD

**Issue by dgrnbrg** [bazelbuild/rules_scala#657]
I’m seeing an issue when switching from SBT to rules_scala, where the ScalaPB-generated field name in the Scala code VS the JSON name in the companion object’s Scala Descriptor no longer match (they used to match perfectly before the changes).

Note that ScalaPB does JSON-ification of field names (camel-casing, removing _, etc), and is supposed to preserve both the original name and the modified name in the Scala Descriptor of the generated companion object. The descriptor no longer contains the generated name, but rather the original only (and it used to).

For example:

```

Field name in the protobuf:        foo30m
Generated Scala field name:       foo30M
Companion’s JSON-ified name:   foo30m

Metadata printout from the Companion’s Field Descriptor:
name: "foo30m"
number: 4
label: LABEL_REPEATED
type: TYPE_DOUBLE
json_name: "foo30m"
```

Do you have any idea what could be causing this?

I have one rule that creates a `proto_library` for the .proto file, and then that's a dependency of a `scalapb_proto_library` which also has `with_grpc=True`.

**Comment by johnynek** [comment]
Thanks for trying these rules.

There are some flags to scalapb that control options. I guess either default settings in sbt are different or the build was configured with different settings.

That or perhaps the version was different and they changed something.

You can see the options it supports in the bottom of this page:
https://scalapb.github.io/scalapbc.html

Maybe read those and see if any seem like they match. Also you might describe the difference in the scalaPB Gitter and see if they know what might have caused it.

**Comment by dgrnbrg** [comment]
Thank you, I have confirmed that this is unrelated to scala rules' integration with scalapb.

**Comment by johnynek** [comment]
Can you give an explanation in case someone else finds this issue?

**Comment by dgrnbrg** [comment]
This was a misunderstanding of the scalapb/protobuf features. It turns out this feature was only just added to scalapb: https://github.com/scalapb/ScalaPB/commit/f6314c49e92017ef32e853417fefe47f16917097

**Comment by ittaiz** [comment]
So if we upgrade you’ll have it? How did you get it on sbt?

**Comment by johnynek** [comment]
I'm worried if this will break people if the default options change in a bump.

**Comment by johnynek** [comment]
(snark: I know bazel users are so used to constant breakage, I probably shouldn't worry)

**Comment by ittaiz** [comment]
I think that our tech debt of toolchains is biting us a lot :(
I really hope to make some time for it in the not so distant future but it
won't happen in the next few weeks.
Unrelated here (but related to tech debt) I hope to tackle the JavaInfo
thing soon
