### ISSUE TITLE
Support blacklisted_protos as in proto_lang_toolchain

### ISSUE THREAD

**Issue by simuons** [bazelbuild/rules_scala#665]
Hi.

**Motivation**
We generate scala code with `flat_package`. We also use `@google_api_protos//google/api:annotations_proto` in our services. Generated code for `annotations.proto` using `flat_package` clashes with google's java clients libraries. So we would like to have `annotations.proto` pre-generated and include it as runtime jar and prevent others to generate clashing code (it gets generated as `proto_library` dep). It would be also useful to stop generating code for well known types because it is already provided by scalapb.

**Solution**
Initially I considered to add support for [proto_lang_toolchain](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_lang_toolchain) (which already have `blacklisted_protos`). Unfortunately according to this https://groups.google.com/forum/#!searchin/bazel-discuss/proto_lang_toolchain%7Csort:date/bazel-discuss/xoy98a4yhAA/hD9eDus9BAAJ it cannot be used from skylark.
Currently I'm thinking about adding `blacklisted_protos` parameter to `scala_proto_srcjar` and remove `blacklisted_protos` from inputs to protoc.

Does it make sense? If yes I'm going to open a PR for this.

**Comment by ittaiz** [comment]
@johnynek did you see this?
