### ISSUE TITLE
Upgrade to latest version of scalapb?

### ISSUE THREAD

**Issue by dgrnbrg** [bazelbuild/rules_scala#667]
Hello, when/how will it be possible to upgrade to a newer scalapb? I'd like to use the features added in this commit: https://github.com/scalapb/ScalaPB/commit/f6314c49e92017ef32e853417fefe47f16917097

**Comment by gseitz** [comment]
@dgrnbrg: Could you try with #691 and see if this works for you?

**Comment by tian000** [comment]
@ittaiz This issue can now be closed. in #1026 I've upgrade to the latest scalapb version that supports 2.11, 2.12. The latest version no longer supports scala 2.11.

**Comment by ittaiz** [comment]
Thanks!
I guess our next iteration will be when we stop supporting 2.11

**Comment by ittaiz** [comment]
Btw, I think this issue should have been closed after #691 was merged (back in Feb 2019) since the op wanted 0.8.4 which is what #691 upgraded to
