### ISSUE TITLE
scala_library shouldn't have a jvm_flags attribute

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#669]
AFAICT scala_library doesn't use `jvm_flags` attribute anymore since we have `scalac_jvm_flags` and `javac_jvm_flags`.
It's only used by binary/repl/test/junit_test which are binary rules.
I'd like to remove it.
On the one hand it's a breaking change OTOH the current attribute is deprecated for many months now.
@johnynek any objections?
cc @aherrmann since I think he was interested in this attribute from #621

**Comment by johnynek** [comment]
I guess it is fine to remove it. It should be easy to migrate since it is a no-op. If people follow the pattern of making their own macro wrapper for rules so they can control default options it would be even easier to migrate: their wrapper can accept the option but just discard it.

**Comment by ittaiz** [comment]
I think bazel people would call this abuse of macros but OTOH I'm not sure
they thoroughly considered the use-case of OSS eco system.
I'll send a PR for this
