### ISSUE TITLE
unused_dependency_checker buildozer commands don't always work

### ISSUE THREAD

**Issue by laurynasl-wix** [bazelbuild/rules_scala#675]
The buildozer commands suggested by unused dependency checker often fail to remove external dependencies. The reason seems to be that there are multiple ways you can refer to a dependency in your BUILD.bazel file and the plugins gets a canonical representation of the dependencies label. 

For example: In my build file I have `deps = ["@unused_dep"]`, but the suggested command is 
```buildozer 'remove deps @unused_dep//:unused_dep'  //foo:bar```. Which fails because buildozer doesn't understand that it's the same label

**Comment by laurynasl-wix** [comment]
One hach around this would be to emit a buildozer command to remove either form of the label:
```buildozer 'remove deps @unused_dep//:unused_dep @unused_dep'  //foo:bar```.

**Comment by laurynasl-wix** [comment]
I think buildozer doesn't really know what's in the attributes you are trying to modify. For `remove` it just expects an attribute name and an attribute value, which is not necessarily a label.

**Comment by ittaiz** [comment]
Not sure. Also maybe they should. Want to open an issue there and ask their
opinion? You can cc me there.
Also can you do the experiment I suggested?
Not sure emitting two labels might not cause an issue with buildozer (error
code 3 or something)

**Comment by laurynasl-wix** [comment]
bazelbuild/buildtools#532

**Comment by laurynasl-wix** [comment]
By bad, turns out I was using an older version of buildozer and it looks like it works in latest
