### ISSUE TITLE
Dependency checkers do not detect scala macro dependencies

### ISSUE THREAD

**Issue by laurynasl-wix** [bazelbuild/rules_scala#679]
It seems like strict/unused dependency checkers do not detect dependencies used by scala macros. The case where I ran into this is the following:

@com_wix_accord_core_2_12 uses @org_scalamacros_resetallattrs_2_12 in its invocation for `com.wix.accord.dsl#validator` macro. Is this is a known limitation?

**Comment by arjantop** [comment]
Is this the same issue? macwire macros dependency is marked unused
https://github.com/arjantop/rules_scala_bug

**Comment by ittaiz** [comment]
Good question, don't know. Summoning @Jamie5 as our resident unused deps expert.

**Comment by Jamie5** [comment]
So the issues are at least similar in that the dependency analyzer is not working properly in both cases. In your case you are using ast mode, and hence is something we can fix (we just need to examine the original macro). I will send out a diff shortly.

(as a side note I am just some random person who knows nothing about anything)

**Comment by Jamie5** [comment]
https://github.com/bazelbuild/rules_scala/pull/1008

(Note, this addresses only ast mode and not high-level mode)

**Comment by ittaiz** [comment]
Thanks! @laurynasl-wix now that I’ve merged #1008 can you check again (and turn on AST mode)?

**Comment by arjantop** [comment]
Thank you @Jamie5 (and everyone involved) for the quick fix!

**Comment by laurynasl-wix** [comment]
We don't face this issue anymore either as we switched to using +1 dependency model (rather then strict), so we don't need to have the transitive dependency explicitly declared in our code. Closing the issue.
