### ISSUE TITLE
Default Scala version should be 2.12 (instead of 2.11)

### ISSUE THREAD

**Issue by natansil** [bazelbuild/rules_scala#703]
Currently the default version is 2.11.12:

https://github.com/bazelbuild/rules_scala/blob/ad41d0ca4f49a712956f5f9ba608cc1d8d47f40f/scala/scala_cross_version.bzl#L25

But according to [JB 2018 survey](https://www.jetbrains.com/research/devecosystem-2018/scala/) only 30% used 2.11, while 64% used 2.12

I think it's time to change the default...

**Comment by ittaiz** [comment]
I agree
@johnynek wdyt?

**Comment by johnynek** [comment]
I agree. I’d like CI to check both 2.11 and 2.12 if possible.

I assume wix is now on 2.12?

**Comment by ittaiz** [comment]
Wix is indeed on 2.12

**Comment by igorgatis** [comment]
At least please make it easy to select, like `scala_repositories(version="2.11")` and `scala_repositories(version="2.12")`

**Comment by johnynek** [comment]
@igorgatis you have seen this right: https://github.com/bazelbuild/rules_scala#selecting-scala-version

Is it that too much?

My feeling is that repo configuration is so rarely done, this isn't a major problem.

**Comment by wisechengyi** [comment]
Twitter has also been on 2.12 for a while. 

Anecdotally I worked on some scalac option related changes having incompatibilities with 2.11.x, which would be resolved if the whole repo switches to 2.12, or at least as the default.

Afacit #962 should not be blocking this and can be worked on separately if needed still, as most folks are on 2.12 already.

Is there objection to switch to 2.12 repo wide?

**Comment by smparkes** [comment]
#962 is close for now and this doesn't block it. But FWIW:

> if needed still, as most folks are on 2.12 already

There's a lot of existing spark code on 2.11. For that community, there's likely to be a long tail of users so maintainers of spark libraries will likely have to support 2.11 for some time.

**Comment by ittaiz** [comment]
I agree about spark and that is why I’m happy we enabled the “test version” test on CI which gives us some sanity into 2.11
