### ISSUE TITLE
specs2 support

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#72]
Hi,
Most of our tests use specs2 (a small portion uses JUnit and a handful use scalatest).
Do you think specs2 support should be part of this library?
If so do you think it should be via a flag to scala_test? via an additional rule?
Not sure I like the fact that scalatest is always on the classpath even if I don't need it but might be negligible.

I can add this support in an external repo but I think it's more natural for it to reside here.

**Comment by ittaiz** [comment]
I'm actually closing this one since we actually use the JUnit runner to run our specs2 tests (`SpecificationWithJUnit`) and so I'll just solve it locally with compiling using the mix_java_scala and then running a JUnit runner ( in sh_test?)

**Comment by johnynek** [comment]
Sorry I didn't reply sooner. I think a scala_specs_test could be fine to
add. I don't see a good way to do it in one rule.

I don't think you need the scalatest dependency if you don't use the rule.

On Monday, June 13, 2016, Ittai Zeidman <notifications@github.com> wrote:

> Closed #72 <https://github.com/bazelbuild/rules_scala/issues/72>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_scala/issues/72#event-691332080>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAEJdkLvZPJ3jc7sV1eQSTlNYnl2y3zCks5qLjKXgaJpZM4Ivzaq>
> .
>


-- 
P. Oscar Boykin, Ph.D. | http://twitter.com/posco | http://pobox.com/~boykin

**Comment by ittaiz** [comment]
No worries at all, hope you enjoyed the getaway and congratulations :)
Do you want me to reopen the issue?
Like I said I don't need this currently but others might. I might even get around to it later on but now I'm trying to face my blockers.

**Comment by johnynek** [comment]
Well, we can leave it closed if you have a work around (at least give us
the impression the issue count is not *too* high. ;)

On Mon, Jun 13, 2016 at 7:14 PM, Ittai Zeidman <notifications@github.com>
wrote:

> No worries at all, hope you enjoyed the getaway and congratulations :)
> Do you want me to reopen the issue?
> Like I said I don't need this currently but others might. I might even get
> around to it later on but now I'm trying to face my blockers.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_scala/issues/72#issuecomment-225781827>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEJdqtXa1OPSqbmpSYFc42GipdO2j0Kks5qLjingaJpZM4Ivzaq>
> .
>



-- 
P. Oscar Boykin, Ph.D. | http://twitter.com/posco | http://pobox.com/~boykin
