### ISSUE TITLE
rule_scala is broken on ci.bazel.io

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_scala#73]
http://ci.bazel.io/job/rules_scala/158/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console

Caused by ebaeff68a0e5cd3b7fd12916a2883fb0b98edd64 which is merged in b471dfe1fb4de04c649a97de9853e84ba81c6267

//cc @johnynek @colinmarc Can you help fix this?

**Comment by colinmarc** [comment]
Look like the issue is that it's running `bazel build //...` instead of `test_run.sh`. There are some build files which we expect to fail in there.

**Comment by damienmg** [comment]
We generally recommend doing integration test that set-up a workspace and call bazel in it so we can actually runs them from Bazel.

ci.bazel.io does build //... and test //..., we can change those pattern if needed.

Also @johnynek if you accept the invite to the bazelbuild org and make the membership public you can trigger the test on ci.bazel.io with "test this please"

**Comment by johnynek** [comment]
@damienmg where can I find that invitation? I have looked several times and see no notification on github for this, and I can't find a good search string:

https://www.dropbox.com/s/n0yu9qsnfqdls9e/Screenshot%202016-06-09%2005.40.52.png?dl=0

**Comment by damienmg** [comment]
I just reinvited you, I hope it work this time.

**Comment by johnynek** [comment]
@damienmg got it.

**Comment by damienmg** [comment]
Ping? What should be done here?

**Comment by johnynek** [comment]
Well. In the short term you could change the test to manually exclude the
failing directories, but as my birthday was Thursday I have taken a few
days off. I can refactor this week to avoid the test script and call Bazel
recursively (I think is your recommendation) so that we set up failing
examples in sh rules I guess?

On Friday, June 10, 2016, Damien Martin-Guillerez <notifications@github.com>
wrote:

> Ping? What should be done here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_scala/issues/73#issuecomment-225162719>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEJdiaTh7Rb2nje04e3lhCY7mJIxQ2Eks5qKVAigaJpZM4Ixtv9>
> .
>


-- 
P. Oscar Boykin, Ph.D. | http://twitter.com/posco | http://pobox.com/~boykin

**Comment by damienmg** [comment]
Plan SGTM. Yes having it has a bazel test is better.

We can just mark the breaking test as "noci" then, I'll send a PR for that.

**Comment by damienmg** [comment]
Send #75 for this.
