### ISSUE TITLE
test_run script doesn't clean hash outputs and doesn't really work on osx vanilla

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#74]
Hi,
AFAIU OS X has md5 and not md5sum which is why I get `./test_run.sh: line 25: md5sum: command not found` when running the script. Don't know if you want this to run on local contributors machines but if it's not important to you maybe it should be noted.
Second problem is that the hash1/hash2 files aren't deleted and aren't ignored.
Sounds to me like they should be deleted if the diff says they're the same. In any case ignoring them could also solve the problem although being a bit more hacky.
One last option is to maybe write them to `bazel-out` which is currently ignored.

What would you like to do with this issue?

**Comment by johnynek** [comment]
As noted in #76 we should run these tests from bazel directly.

If we do that, we can probably use java program to compute the md5, which would be portable.

How does that sound?

**Comment by ittaiz** [comment]
Sounds good. Closing.
