### ISSUE TITLE
README documentation on scalapb_proto_library is outdated

### ISSUE THREAD

**Issue by steinar** [bazelbuild/rules_scala#744]
[README documentation on scalapb_proto_library](https://github.com/bazelbuild/rules_scala/blob/master/docs/scalapb_proto_library.md) lists a number of arguments which were moved to `scala_proto_toolchain` in #700.

The documentation suggest one should do the following to include gRPC:

```python
scalapb_proto_library(
    name='ping_scala',
    deps=[':ping'],
    with_grpc = True,
)
```

Which will result in an error as `with_grpc` argument is unexpected for `scalapb_proto_library`. Instead you must overwrite the toolchain in your BUILD file:

```python
load("@io_bazel_rules_scala//scala_proto:scala_proto_toolchain.bzl", "scala_proto_toolchain")

scala_proto_toolchain(
    name = "scala_proto_toolchain_configuration",
    with_grpc = False,
)

toolchain(
    name = "scalapb_toolchain",
    toolchain = ":scala_proto_toolchain_configuration",
    toolchain_type = "@io_bazel_rules_scala//scala_proto:toolchain_type",
    visibility = ["//visibility:public"],
)
```

AFAIK this change is not documented anywhere.

**Comment by johnynek** [comment]
yes that's right. A PR to improve the documentation would be welcomed!
