### ISSUE TITLE
windows CI is flaky

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#749]
see: https://travis-ci.org/bazelbuild/rules_scala/jobs/531959514#L436

cc @majcherm-da 

this has shown up in: #748 and #745

**Comment by johnynek** [comment]
I've seen this several times...

I wonder if it is flaky locally or if travis is flaky for windows.

**Comment by ittaiz** [comment]
I've seen another different issue of windows flakiness attached here (I actually saw two different ones but don't have the log of the other)
[failing_windows_travis_log.txt](https://github.com/bazelbuild/rules_scala/files/3414497/failing_windows_travis_log.txt)
@majcherm-da do you think you'll have some capacity to take a look?

**Comment by johnynek** [comment]
I think proto tests should just be disabled on windows until someone interested wants to invest the time to get them passing.

**Comment by ittaiz** [comment]
+1.
We should probably decide that this is the policy for most tests that flake
out after some time.
The unification Andy sent will probably make this a bit more complicated
bash setup wise

**Comment by andyscott** [comment]
I'd prefer that we wait-- I intend to split apart the test scripts so it's easy to tag which tests run for each configuration.

**Comment by ittaiz** [comment]
👍🏽
One note though- long term vision IMHO should be to move the bash tests
inside Bazel using bazel-integration-testing library.
If you’re doing a small medium effort that’s ok but if you’re going to be
doing a large one then maybe we should reconsider investing in moving over
to it.
