### ISSUE TITLE
Including Dependencies in the JAR ?

### ISSUE THREAD

**Issue by amit-traiana** [bazelbuild/rules_scala#844]
Hello :-)

We are using Bazel to generate Protobuf code in multiple languages. However, the resulted Scala JAR (generated by `scala_proto_library`) is a bit inconsistent with how the Java JAR looks like. The Java JAR include all the dependencies stated in the rule in transitive fashion. So if you rule for example stating `empty.proto` and `//local:service_proto` as dependencies - the Java Jar will bundle the classes for those two dependencies into the Java JAR file. With `scala_proto_library` - the only classes in the JAR is the generated code for the root project, dependencies are excluded.

It means that when using the JAR, we have to also manually grab the dependencies, where in the Java JAR we get all dependencies needed for the code to work in a single JAR.

Is that something I can control? I was checking the Toolchain parameters, but all are Scalapb options rather than how the Jar is being built?

Thanks!

**Comment by ittaiz** [comment]
Hi Amit,
How do you generate the java jar file?
We actually had the situation which you’re describing but moved off of it
since it meant generating/compiling the same files all over again. AFAIK
java doesn’t generate it multiple times so I’m wondering if your usage
might be different

**Comment by amit-traiana** [comment]
Shalom Ittai :-)

We try to stick to the `bazelbuild` rules when possible, but I was just checking the rule we are using in Java and it's actually not the one that comes build-in into Bazel. We are using [this](https://github.com/stackb/rules_proto/tree/master/java#java_grpc_library) rule for Java. The reason we opts for this one over the one that comes build-in into Bazel, was because the build-in actually create two JARs - one for gRPC classes, and one for Protobuf messages -  which is a bit strange and require each consumer depend on TWO jars that represent the same service. So we went with `rules_proto` repository instead that create a single JAR with both gRPC and protobuf message in it (and include all dependencies in it).

I wonder how you guys handle dependencies when using `scala_proto_library`? Because if the Protobuf file depends on protobuf files from other projects, you need to manually explicitly add those to your project (and if those require their own external protos - you need to include them too - and that's a big dependency chain to be aware about as a micro-service developer who consume a single service API).

Thanks!

**Comment by ittaiz** [comment]
I think we have a bit of confusion here.
Bazel does have some concept of transitive dependencies. It doesn’t have it for external workspaces so maybe that what you mean.
Any chance you can share a snippet of expected/actual build graph?

Re two targets of rules_proto of bazelbuild (as opposed to stackb rules)- sounds like you can just expose a macro for internal use that translates to three targets:
gRPC, protobuf and a third one that exports them. Again given an example I can better illustrate my point.

**Comment by ittaiz** [comment]
@ianoc any chance you can contribute a short readme about why we chose to design protobuf with an aspect? It could have helped this discussion.

**Comment by ianoc** [comment]
@ittaiz I  can add something but we are just following along the same as how the java rules are implemented in bazel --  https://blog.bazel.build/2017/02/27/protocol-buffers.html

**Comment by ittaiz** [comment]
Amit,
Any chance you can read that blog post and see if explains our motivation?

**Comment by amit-traiana** [comment]
Hi @ittaiz and @ianoc,

I wrote a minimalistic example and it looks like your right and you do follow the way the official rule handles it:

This [branch](https://github.com/amit-traiana/Bazel-Example) uses the [rules_proto](https://github.com/stackb/rules_proto/tree/master/java#java_proto_library) gRPC library implementation. If you will build the whole solution (`bazel build //...`) and check the `bazel-bin/service_b` folder you will see two JARs -  the Java JAR (`libservice_b_java_proto.jar`) has class files for both `service_b` and his dependency `service_a` in it. The Scala JAR on the other hand (`service_b_proto_scalapb.jar`) has only the `service_b` classes.

On the other hand, this [branch](https://github.com/amit-traiana/Bazel-Example/tree/example_b) uses the [grpc-java](https://github.com/grpc/grpc-java) gRPC library implementation. If you will build the project again and check the Java JAR this branch creates, it like the Scala JAR only has `service_b` classes in it.

So it's looks like `rules_proto` gRPC rule implementation do something non standard by adding both services classes into a single JAR.

If that's the case, it's a problem for us. Because we only compile generated Protobuf code with Bazel. So if a Gradle project for example would like to use this JAR - we will have to manually state inside Gradle which dependencies this JAR is using, or create a POM file specifically for it. Unless we migrate all the Gradle projects into Bazel so they can just call the 'rule' instead of using the JAR. But that's our problem anyhow - and not yours :-)

So if my example makes sense to you - it's probably mean you can close this issue. Thanks and sorry for the hassle!

**Comment by ittaiz** [comment]
Good luck.
Not sure I understand how you’re currently exporting the jars from bazel to gradle but it shouldn’t be dramatically different for simple graphs and simple “exported gradle module”. Search for bazel aspects for a hint.
Also consider coming to bazelbuild slack.

**Comment by amit-traiana** [comment]
Thank @ittaiz!

The reason why I was looking for a self-contained JAR with all dependencies in it - is because we don't use Bazel across all projects here. All project however - use Artifactory as a meaning to share dependencies. The JAR that is being created with `scala_proto_library` and the default Java rule can't be published into Maven without a POM file that state dependencies. I don't use Gradle, but if I recall correctly Bazel works the same. If your work inside the boundaries of Gradle - you can reference the a Project (much like you can reference directly to a target in remote repository with Bazel). But if you want to share the JAR with another build system (that consume MVN) - you have to have a POM file that state dependencies. Gradle has a build in MVN plug-in that does that - Bazel don't.

I did find couple of external Bazel rules that generated POM file, but they required a rules that  produce any java_library srcs files. The `scala_proto_library` generate a JAR and not just compiled proto files, so I can't chains those two rules together. Would you consider create a new rule that generate just classes? See [those](https://github.com/stackb/rules_proto/tree/master/scala#scala_proto_compile) scalapb rules for example.You can either create a library (jar) using `scala_grpc_library` or if you want just the compiled class files (so you can use this rule as input to other rules) - you can use `scala_grpc_compile`.

I never heard of Bazel Aspects. I'll give it a look - Maybe this will help me solve the problem.
Thank you!
