### ISSUE TITLE
[Question] Possible to run tests serially?

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/rules_scala#852]
I know tests run by Bazel should be hermetic so that it can run tests concurrently. Unfortunately for those of us who are coming from SBT and do not write hermetic tests, this is a difficult transition.

I'm wondering if there's a way to temporarily configure Bazel to run tests serially.

**Comment by KaoruDev** [comment]
@ittaiz thanks for the help! `bazel test --local_test_runs=1 //target:test` returns: `ERROR: Unrecognized option: --local_test_runs=1` 😞

**Comment by KaoruDev** [comment]
Note: I found the culprit in my tests, Joda time 😉 , I worked around it by isolated these test as their own targets and running them `exclusively`. Doesn't solve my initial question, but maybe a reasonable workaround for now.

**Comment by ittaiz** [comment]
—local_test_jobs for future people

**Comment by sdtwigg** [comment]
You can also tag a test target with "exclusive" and all exclusion tests
will run serially after all non-exclusive tests and build actions.

https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes

**Comment by KaoruDev** [comment]
@sdtwigg true, but I believe that Suites within a test Target still run concurrently. I observed the same test failures even after I added the "exclusive" flag to my test Target 😭

**Comment by KaoruDev** [comment]
@ittaiz `--local_test_jobs=1` is a valid param, alas the problem isn't fixed. When I have a minute I'll try to set up a repo with an example.

If I had to guess, the job has a threadpool which executes different Scalatest suites concurrently.
