### ISSUE TITLE
Bazel 1.0.0 Compatibility

### ISSUE THREAD

**Issue by thundergolfer** [bazelbuild/rules_scala#862]
### Description

Bumping `rules_scala` to current `HEAD`, `f985e5e0d6364970be8d6f15d262c8b0e0973d1b`, allowed me to build a very minimal amount of Scala code (in [thundergolfer/the-one-true-bazel-monorepo](https://github.com/thundergolfer/the-one-true-bazel-monorepo)) using Bazel 1.0.0. Reassuring, but hardly a proper test of compatibility.

The `README` currently doesn't list `1.0.0` in its compatibility table, so I'm opening this issue to highlight that and track `1.0.0` compatibility. 

Thanks for all the work on these rules. Hopefully I can contribute back someday 🙂.

**Comment by johnynek** [comment]
See #861 — all tests pass.

Why not send your first PR as a note in the README that 1.0 is supported?

**Comment by ittaiz** [comment]
readme is updated. We're using bazel 2.0 and rules_scala on prod
