### ISSUE TITLE
Simple example repo for building scala and protobuf with bazel

### ISSUE THREAD

**Issue by abhandaru** [bazelbuild/rules_scala#873]
Hi team. First off, thank you for this excellent software.

I am trying to get started with **protobuf** in an existing `scala` repository that builds with `bazel`. Some simple search attempts largely came up empty when trying to find a minimal example (which I would then try and integrate).

---

TLDR; I am trying to get this small example of my own to run:
https://github.com/abhandaru/bazel-scala-proto-example

Any advice, re-labeling of this issue, or pointers to solutions would be hugely appreciated.

The [example project](https://github.com/abhandaru/bazel-scala-proto-example) above contains the following:

* A `README.md` with `bazel` settings, command used, and error output
* A `WORKSPACE` file with `scala`, `protobuf`, and `rules_scala` versions
    * These versions might be stale, happy to retry with suggested SHAs
* A `src/example` folder with a `BUILD` file and two source files

---

Thank you for taking a look. Let me know if the issue format needs any changes.

**Comment by abhandaru** [comment]
Okay, solution found.

The [`ScalaPB` documentation](https://scalapb.github.io/generated-code.html) covers my mistake. The name of the file without the extension is appended to the package name. This is different from how it works with the `java` bindings, where you can specify the exact name on the `CLASSPATH`. 

I have updated my example and it builds just fine.
Will close the issue as resolved, but let me know if you find the repo useful (otherwise I can delete it)

**Comment by ittaiz** [comment]
Glad to hear it’s resolved!
I don’t need the repo but the community and people coming from google might.
