### ISSUE TITLE
WORKSPACE recipe in README.md does not work with Bazel 1.0

### ISSUE THREAD

**Issue by t-soliduslink** [bazelbuild/rules_scala#876]
`README.md` points to commit 69d3c5b5d9b51537231746e93b4383384c9ebcf4 which is just before's Irina Iancu's commit 3404be0e3b3afda99a12724171d80283eaf2b1e7  which replaced `java_common.create_provider` with `JavaInfo()`. Bazel 1.0 removed `java_common.create_provider` (see [Release Notes](https://blog.bazel.build/2019/10/10/bazel-1.0.html))

So people who just copy&paste the recipe will experience a build failure.

**Comment by ittaiz** [comment]
Thanks! Interested in sending us a PR for this?

**Comment by liucijus** [comment]
Seems to be solved by https://github.com/bazelbuild/rules_scala/pull/1022
