### ISSUE TITLE
wrong hash in dependencies gives a silent failure

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#891]
if you put the wrong hash in the build file, it will not report any error, it just won't put the jar on the classpath and you get a compilation error.

This is a painful debugging experience.

I think the jvm_import_external rule should report an error, not silently filter jars, when the hashes don't match.

cc @jin

**Comment by ittaiz** [comment]
Which build file? Do you mean the sha256 in a .bzl file? When you say wrong, what do you mean? Incorrect or of a different jar? Maybe you’re referring to https://github.com/bazelbuild/bazel/issues/5144?

**Comment by jin** [comment]
This is most definitely bazelbuild/bazel#5144, and a proposed fix is https://github.com/bazelbuild/bazel/issues/10353#issuecomment-561614474

**Comment by johnynek** [comment]
It was in the scala_repositories.bzl file where we declare dependencies.

Yeah, I copy-pasted a hash assuming it would error and tell me the right hash but I guess it just uses the content addressed hash and that gives the errors I saw.
