### ISSUE TITLE
External jar fetch from private S3 bucket

### ISSUE THREAD

**Issue by gmendonca** [bazelbuild/rules_scala#911]
I'm trying to use `bazel-deps` to resolve maven dependencies on AWS S3 with `coursier`(see https://github.com/johnynek/bazel-deps/pull/275 and https://github.com/coursier/coursier/issues/1488). If this works out, there's still something that I think it needs to be done here, I might be wrong, so bear with me.

Since `bazel-deps` puts the jars under `//external:jar/`, I'm assuming `scala_maven_import_external` needs to be able to recognise and download `s3://` jar paths when building the project with such dependencies.

**Comment by ittaiz** [comment]
`scala_maven_import_external` underneath uses [repository_ctx.download](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#download). This [recently](https://github.com/bazelbuild/bazel/issues/9327) got authentication support (1.2.1?).
I think these are the bits you need to get in place.
Don't know a lot more though.
Good luck.

**Comment by ittaiz** [comment]
@gmendonca can we close this?

**Comment by gmendonca** [comment]
Yeah, sure. There's a FR on bazel already. Thanks!
