### ISSUE TITLE
central.maven.org is down and downloading rules_scala dependencies fails on empty cache

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/rules_scala#925]
Several rules_scala dependencies are hard coded to use central.maven.org repository.
central.maven.org seems to be down.

If I set up a bazel project with rules_scala and try to build it on an empty cache I'll receive the following error:

WARNING: Download from http://central.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 501 HTTPS Required
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_scala_scala_library':
   java.io.IOException: Error downloading [http://central.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar] to /home/user/.cache/bazel/_bazel_user/3d8061b6974a562053f8cafe6e4c4b30/external/io_bazel_rules_scala_scala_library/scala-library-2.11.12.jar: GET returned 501 HTTPS Required

Steps to reproduce this problem:

git clone https://github.com/gergelyfabian/bazel-scala-example
cd bazel-scala-example
bazel build //...

**Comment by gergelyfabian** [comment]
It seems this is not a problem for the latest version.

**Comment by ittaiz** [comment]
Indeed, it was fixed a few hours ago
