### ISSUE TITLE
Remove Repository Pattern to Toolchain

### ISSUE THREAD

**Issue by borkaehw** [bazelbuild/rules_scala#993]
Move `*_repositories` to a toolchain. It includes
- jmh_repositories
- junit_repositories
- scala_repositories
- scalafmt_repositories
- scala_proto_repositories
- specs2_repositories
- specs2_junit_repositories
- tut_repositories

I may miss some.

**Comment by ittaiz** [comment]
Isn’t it a duplicate of #940 ?

**Comment by borkaehw** [comment]
That's right, sorry for that. Would you mind to make sure the items I listed are mentioned in #940? Then I will close it.

**Comment by ittaiz** [comment]
Most are there. `scala_repositories` isn't there but that's a much larger discussion that's taking place.
`junit` and `specs2_junit` aren't there but `specs2` is.
Not sure if `junit`/`specs2_junit` should be a top level toolchain

**Comment by borkaehw** [comment]
Thanks for making sure. Also make sure `scalafmt` is there as well. Closing it now.
